USE [master]
GO

/****** Object:  Database [LOG]    Script Date: 12/08/2022 15:55:06 ******/
CREATE DATABASE [LOG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LOG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LOG.mdf' , SIZE = 8855552KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LOG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LOG_log.ldf' , SIZE = 466944KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LOG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LOG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LOG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LOG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LOG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LOG] SET ARITHABORT OFF 
GO

ALTER DATABASE [LOG] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LOG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LOG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LOG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LOG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LOG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LOG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LOG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LOG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LOG] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LOG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LOG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LOG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LOG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LOG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LOG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LOG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LOG] SET RECOVERY FULL 
GO

ALTER DATABASE [LOG] SET  MULTI_USER 
GO

ALTER DATABASE [LOG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LOG] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LOG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LOG] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LOG] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LOG] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LOG] SET  READ_WRITE 
GO


