'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 1.1.4322.573.
'
Namespace WS_Box16
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsGetBox16Soap", [Namespace]:="http://tempuri.org/WSbox16/wsGetBox16")>  _
    Public Class wsGetBox16
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://rmshp6/WSbox16/WSGetBox16.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSbox16/wsGetBox16/GeneraFile", RequestNamespace:="http://tempuri.org/WSbox16/wsGetBox16", ResponseNamespace:="http://tempuri.org/WSbox16/wsGetBox16", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GeneraFile(ByVal idBandoAttivita As Integer, ByVal username As String) As String
            Dim results() As Object = Me.Invoke("GeneraFile", New Object() {idBandoAttivita, username})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGeneraFile(ByVal idBandoAttivita As Integer, ByVal username As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GeneraFile", New Object() {idBandoAttivita, username}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGeneraFile(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
