'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace WS_Editor
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSMetodiDocumentazioneSoap", [Namespace]:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione")>  _
    Partial Public Class WSMetodiDocumentazione
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RecuperaTemplateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ScriviTemplateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GenerazioneBOX16_BOX19OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Async_InserimentoDocumentiProgettiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Async_COMP_ElaborazioneOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GenerazioneAllegato6_ElencoSediOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Futuro.My.MySettings.Default.Futuro_WS_Editor_WSMetodiDocumentazione
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RecuperaTemplateCompleted As RecuperaTemplateCompletedEventHandler
        
        '''<remarks/>
        Public Event ScriviTemplateCompleted As ScriviTemplateCompletedEventHandler
        
        '''<remarks/>
        Public Event GenerazioneBOX16_BOX19Completed As GenerazioneBOX16_BOX19CompletedEventHandler
        
        '''<remarks/>
        Public Event Async_InserimentoDocumentiProgettiCompleted As Async_InserimentoDocumentiProgettiCompletedEventHandler
        
        '''<remarks/>
        Public Event Async_COMP_ElaborazioneCompleted As Async_COMP_ElaborazioneCompletedEventHandler
        
        '''<remarks/>
        Public Event GenerazioneAllegato6_ElencoSediCompleted As GenerazioneAllegato6_ElencoSediCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione/RecuperaTemplate", RequestNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", ResponseNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RecuperaTemplate(ByVal strPath As String, ByVal strNomeFile As String) As String
            Dim results() As Object = Me.Invoke("RecuperaTemplate", New Object() {strPath, strNomeFile})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecuperaTemplateAsync(ByVal strPath As String, ByVal strNomeFile As String)
            Me.RecuperaTemplateAsync(strPath, strNomeFile, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecuperaTemplateAsync(ByVal strPath As String, ByVal strNomeFile As String, ByVal userState As Object)
            If (Me.RecuperaTemplateOperationCompleted Is Nothing) Then
                Me.RecuperaTemplateOperationCompleted = AddressOf Me.OnRecuperaTemplateOperationCompleted
            End If
            Me.InvokeAsync("RecuperaTemplate", New Object() {strPath, strNomeFile}, Me.RecuperaTemplateOperationCompleted, userState)
        End Sub
        
        Private Sub OnRecuperaTemplateOperationCompleted(ByVal arg As Object)
            If (Not (Me.RecuperaTemplateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecuperaTemplateCompleted(Me, New RecuperaTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione/ScriviTemplate", RequestNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", ResponseNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ScriviTemplate(ByVal strPath As String, ByVal strFileBase64 As String, ByVal strNomeFile As String) As Object
            Dim results() As Object = Me.Invoke("ScriviTemplate", New Object() {strPath, strFileBase64, strNomeFile})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ScriviTemplateAsync(ByVal strPath As String, ByVal strFileBase64 As String, ByVal strNomeFile As String)
            Me.ScriviTemplateAsync(strPath, strFileBase64, strNomeFile, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ScriviTemplateAsync(ByVal strPath As String, ByVal strFileBase64 As String, ByVal strNomeFile As String, ByVal userState As Object)
            If (Me.ScriviTemplateOperationCompleted Is Nothing) Then
                Me.ScriviTemplateOperationCompleted = AddressOf Me.OnScriviTemplateOperationCompleted
            End If
            Me.InvokeAsync("ScriviTemplate", New Object() {strPath, strFileBase64, strNomeFile}, Me.ScriviTemplateOperationCompleted, userState)
        End Sub
        
        Private Sub OnScriviTemplateOperationCompleted(ByVal arg As Object)
            If (Not (Me.ScriviTemplateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ScriviTemplateCompleted(Me, New ScriviTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione/GenerazioneBOX16_BOX19"& _ 
            "", RequestNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", ResponseNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GenerazioneBOX16_BOX19(ByVal IdBandoAttivita As Integer, ByVal NomeUtente As String) As Object
            Dim results() As Object = Me.Invoke("GenerazioneBOX16_BOX19", New Object() {IdBandoAttivita, NomeUtente})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GenerazioneBOX16_BOX19Async(ByVal IdBandoAttivita As Integer, ByVal NomeUtente As String)
            Me.GenerazioneBOX16_BOX19Async(IdBandoAttivita, NomeUtente, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GenerazioneBOX16_BOX19Async(ByVal IdBandoAttivita As Integer, ByVal NomeUtente As String, ByVal userState As Object)
            If (Me.GenerazioneBOX16_BOX19OperationCompleted Is Nothing) Then
                Me.GenerazioneBOX16_BOX19OperationCompleted = AddressOf Me.OnGenerazioneBOX16_BOX19OperationCompleted
            End If
            Me.InvokeAsync("GenerazioneBOX16_BOX19", New Object() {IdBandoAttivita, NomeUtente}, Me.GenerazioneBOX16_BOX19OperationCompleted, userState)
        End Sub
        
        Private Sub OnGenerazioneBOX16_BOX19OperationCompleted(ByVal arg As Object)
            If (Not (Me.GenerazioneBOX16_BOX19CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GenerazioneBOX16_BOX19Completed(Me, New GenerazioneBOX16_BOX19CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione/Async_InserimentoDocum"& _ 
            "entiProgetti", RequestNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", ResponseNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Async_InserimentoDocumentiProgetti(ByVal IdAttività As String, ByVal IdAttivitaDocumento As String, ByVal username As String) As String
            Dim results() As Object = Me.Invoke("Async_InserimentoDocumentiProgetti", New Object() {IdAttività, IdAttivitaDocumento, username})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Async_InserimentoDocumentiProgettiAsync(ByVal IdAttività As String, ByVal IdAttivitaDocumento As String, ByVal username As String)
            Me.Async_InserimentoDocumentiProgettiAsync(IdAttività, IdAttivitaDocumento, username, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Async_InserimentoDocumentiProgettiAsync(ByVal IdAttività As String, ByVal IdAttivitaDocumento As String, ByVal username As String, ByVal userState As Object)
            If (Me.Async_InserimentoDocumentiProgettiOperationCompleted Is Nothing) Then
                Me.Async_InserimentoDocumentiProgettiOperationCompleted = AddressOf Me.OnAsync_InserimentoDocumentiProgettiOperationCompleted
            End If
            Me.InvokeAsync("Async_InserimentoDocumentiProgetti", New Object() {IdAttività, IdAttivitaDocumento, username}, Me.Async_InserimentoDocumentiProgettiOperationCompleted, userState)
        End Sub
        
        Private Sub OnAsync_InserimentoDocumentiProgettiOperationCompleted(ByVal arg As Object)
            If (Not (Me.Async_InserimentoDocumentiProgettiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Async_InserimentoDocumentiProgettiCompleted(Me, New Async_InserimentoDocumentiProgettiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione/Async_COMP_Elaborazion"& _ 
            "e", RequestNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", ResponseNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Async_COMP_Elaborazione(ByVal IdElaborazione As String, ByVal UserNameRichiesta As String) As String
            Dim results() As Object = Me.Invoke("Async_COMP_Elaborazione", New Object() {IdElaborazione, UserNameRichiesta})
            Return CType(results(0),String)
        End Function
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione/getBox", RequestNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", ResponseNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function getBox(ByVal IdBandoAtttivita As Integer, ByVal username As String, ByVal nomereport As String) As String
            Dim results() As Object = Me.Invoke("getBox", New Object() {IdBandoAtttivita, username, nomereport})
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Function BeginAsync_InserimentoDocumentiProgetti(ByVal IdAttività As String, ByVal IdAttivitaDocumento As String, ByVal username As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Async_InserimentoDocumentiProgetti", New Object() {IdAttività, IdAttivitaDocumento, username}, callback, asyncState)
        End Function


        '''<remarks/>
        Public Function BeginGenerazioneBOX16_BOX19(ByVal IdBandoAttivita As Integer, ByVal NomeUtente As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GenerazioneBOX16_BOX19", New Object() {IdBandoAttivita, NomeUtente}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function BeginGenerazioneAllegato6_ElencoSedi(ByVal IdEnteFase As Integer, ByVal NomeUtente As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GenerazioneAllegato6_ElencoSedi", New Object() {IdEnteFase, NomeUtente}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Overloads Sub Async_COMP_ElaborazioneAsync(ByVal IdElaborazione As String, ByVal UserNameRichiesta As String)
            Me.Async_COMP_ElaborazioneAsync(IdElaborazione, UserNameRichiesta, Nothing)
        End Sub

        '''<remarks/>
        Public Function BeginAsync_COMP_Elaborazione(ByVal IdElaborazione As String, ByVal UserNameRichiesta As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Async_COMP_Elaborazione", New Object() {IdElaborazione, UserNameRichiesta}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Overloads Sub Async_COMP_ElaborazioneAsync(ByVal IdElaborazione As String, ByVal UserNameRichiesta As String, ByVal userState As Object)
            If (Me.Async_COMP_ElaborazioneOperationCompleted Is Nothing) Then
                Me.Async_COMP_ElaborazioneOperationCompleted = AddressOf Me.OnAsync_COMP_ElaborazioneOperationCompleted
            End If
            Me.InvokeAsync("Async_COMP_Elaborazione", New Object() {IdElaborazione, UserNameRichiesta}, Me.Async_COMP_ElaborazioneOperationCompleted, userState)
        End Sub
        
        Private Sub OnAsync_COMP_ElaborazioneOperationCompleted(ByVal arg As Object)
            If (Not (Me.Async_COMP_ElaborazioneCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Async_COMP_ElaborazioneCompleted(Me, New Async_COMP_ElaborazioneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione/GenerazioneAllegato6_E"& _ 
            "lencoSedi", RequestNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", ResponseNamespace:="http://tempuri.org/WSDocumentazione/WSMetodiDocumentazione", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GenerazioneAllegato6_ElencoSedi(ByVal IdEnteFase As Integer, ByVal NomeUtente As String) As Object
            Dim results() As Object = Me.Invoke("GenerazioneAllegato6_ElencoSedi", New Object() {IdEnteFase, NomeUtente})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GenerazioneAllegato6_ElencoSediAsync(ByVal IdEnteFase As Integer, ByVal NomeUtente As String)
            Me.GenerazioneAllegato6_ElencoSediAsync(IdEnteFase, NomeUtente, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GenerazioneAllegato6_ElencoSediAsync(ByVal IdEnteFase As Integer, ByVal NomeUtente As String, ByVal userState As Object)
            If (Me.GenerazioneAllegato6_ElencoSediOperationCompleted Is Nothing) Then
                Me.GenerazioneAllegato6_ElencoSediOperationCompleted = AddressOf Me.OnGenerazioneAllegato6_ElencoSediOperationCompleted
            End If
            Me.InvokeAsync("GenerazioneAllegato6_ElencoSedi", New Object() {IdEnteFase, NomeUtente}, Me.GenerazioneAllegato6_ElencoSediOperationCompleted, userState)
        End Sub
        
        Private Sub OnGenerazioneAllegato6_ElencoSediOperationCompleted(ByVal arg As Object)
            If (Not (Me.GenerazioneAllegato6_ElencoSediCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GenerazioneAllegato6_ElencoSediCompleted(Me, New GenerazioneAllegato6_ElencoSediCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub RecuperaTemplateCompletedEventHandler(ByVal sender As Object, ByVal e As RecuperaTemplateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecuperaTemplateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub ScriviTemplateCompletedEventHandler(ByVal sender As Object, ByVal e As ScriviTemplateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ScriviTemplateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub GenerazioneBOX16_BOX19CompletedEventHandler(ByVal sender As Object, ByVal e As GenerazioneBOX16_BOX19CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GenerazioneBOX16_BOX19CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Async_InserimentoDocumentiProgettiCompletedEventHandler(ByVal sender As Object, ByVal e As Async_InserimentoDocumentiProgettiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Async_InserimentoDocumentiProgettiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub Async_COMP_ElaborazioneCompletedEventHandler(ByVal sender As Object, ByVal e As Async_COMP_ElaborazioneCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Async_COMP_ElaborazioneCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub GenerazioneAllegato6_ElencoSediCompletedEventHandler(ByVal sender As Object, ByVal e As GenerazioneAllegato6_ElencoSediCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GenerazioneAllegato6_ElencoSediCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
End Namespace
