//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomandaPresentata
    {
        public int Id { get; set; }
        public string CodiceFiscale { get; set; }
        public int GruppoBando { get; set; }
        public System.DateTime DataInserimento { get; set; }
        public string UserIdModifica { get; set; }
        public Nullable<System.DateTime> DataModifica { get; set; }
        public string CodiceProgettoSelezionato { get; set; }
        public Nullable<int> CodiceSedeSelezionata { get; set; }
        public Nullable<System.DateTime> DataPresentazione { get; set; }
        public Nullable<System.DateTime> DataAnnullamento { get; set; }
        public string NomeFileCV { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Genere { get; set; }
        public Nullable<System.DateTime> DataNascita { get; set; }
        public string LuogoNascita { get; set; }
        public string NazioneNascita { get; set; }
        public string Cittadinanza { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string ComuneResidenza { get; set; }
        public string ProvinciaResidenza { get; set; }
        public string ViaResidenza { get; set; }
        public string CivicoResidenza { get; set; }
        public string CapResidenza { get; set; }
        public string IndirizoCompleto { get; set; }
        public string ComuneRecapito { get; set; }
        public string ProvinciaRecapito { get; set; }
        public string ViaRecapito { get; set; }
        public string CivicoRecapito { get; set; }
        public string CapRecapito { get; set; }
        public string CodiceMinoriOpportunita { get; set; }
        public Nullable<int> IdMotivazione { get; set; }
        public string Motivazione { get; set; }
        public string CodiceDichiarazioneCittadinanza { get; set; }
        public Nullable<bool> NonCondanneOk { get; set; }
        public Nullable<bool> TrasferimentoSedeOk { get; set; }
        public Nullable<bool> TrasferimentoProgettoOk { get; set; }
        public Nullable<bool> AltreDichiarazioniOk { get; set; }
        public Nullable<int> IdTitoloStudio { get; set; }
        public string TitoloStudio { get; set; }
        public Nullable<bool> PrivacyPresaVisione { get; set; }
        public Nullable<bool> PrivacyConsenso { get; set; }
        public Nullable<bool> PrecedentiEnte { get; set; }
        public string PrecedentiEnteDescrizione { get; set; }
        public Nullable<bool> PrecedentiAltriEnti { get; set; }
        public string PrecedentiAltriEntiDescrizione { get; set; }
        public Nullable<bool> PrecedentiImpiego { get; set; }
        public string PrecedentiImpiegoDescrizione { get; set; }
        public Nullable<int> IdTitoloStudioEsperienze { get; set; }
        public string TitoloStudioEsperienze { get; set; }
        public string FormazioneDisciplina { get; set; }
        public Nullable<int> FormazioneAnno { get; set; }
        public Nullable<System.DateTime> FormazioneData { get; set; }
        public Nullable<bool> FormazioneItalia { get; set; }
        public string FormazioneIstituto { get; set; }
        public string FormazioneEnte { get; set; }
        public Nullable<int> IscrizioneSuperioreAnno { get; set; }
        public string IscrizioneSuperioreIstituto { get; set; }
        public Nullable<int> IscrizioneLaureaAnno { get; set; }
        public string IscrizioneLaureaCorso { get; set; }
        public string IscrizioneLaureaIstituto { get; set; }
        public string CorsiEffettuati { get; set; }
        public string Specializzazioni { get; set; }
        public string Competenze { get; set; }
        public string Altro { get; set; }
        public Nullable<System.DateTime> DataInizioProtocollazione { get; set; }
        public Nullable<System.DateTime> DataFineProtocollazione { get; set; }
        public string CODICEPROTOCOLLO { get; set; }
        public string NUMEROPROTOCOLLO { get; set; }
        public Nullable<System.DateTime> DATAPROTOCOLLO { get; set; }
        public Nullable<System.DateTime> DataInvioPEC { get; set; }
        public string NazioneResidenza { get; set; }
        public string IndirizzoCompletoResidenza { get; set; }
        public Nullable<bool> ResidenzaEstera { get; set; }
        public Nullable<System.DateTime> DataInizioProtocollazioneAnnullamento { get; set; }
        public Nullable<System.DateTime> DataFineProtocollazioneAnnullamento { get; set; }
        public string CODICEPROTOCOLLOAnnullamento { get; set; }
        public string NUMEROPROTOCOLLOAnnullamento { get; set; }
        public Nullable<System.DateTime> DATAPROTOCOLLOAnnullamento { get; set; }
        public Nullable<System.DateTime> DataInvioPECAnnullamento { get; set; }
        public Nullable<System.DateTime> DataRichiestaAnnullamento { get; set; }
        public string MotivoAnnullamento { get; set; }
        public string FormazioneAnagraficaDisciplina { get; set; }
        public Nullable<int> FormazioneAnagraficaAnno { get; set; }
        public Nullable<bool> FormazioneAnagraficaItalia { get; set; }
        public string FormazioneAnagraficaIstituto { get; set; }
        public string FormazioneAnagraficaEnte { get; set; }
        public Nullable<bool> DichiarazioneResidenzaOK { get; set; }
        public Nullable<bool> DichiarazioneRequisitiGaranziaGiovani { get; set; }
        public Nullable<System.DateTime> DataPresaInCaricoGaranziaGiovani { get; set; }
        public string LuogoPresaInCaricoGaranziaGiovani { get; set; }
        public Nullable<System.DateTime> DataDIDGaranziaGiovani { get; set; }
        public string LuogoDIDGaranziaGiovani { get; set; }
        public Nullable<bool> AlternativaRequisitiGaranziaGiovani { get; set; }
        public Nullable<bool> DichiarazioneMinoriOpportunita { get; set; }
    }
}
