//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleAgent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HeliosContext : DbContext
    {
        public HeliosContext()
            : base("name=HeliosContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DomandaPresentata> DomandaPresentata { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobSchedule> JobSchedule { get; set; }
        public virtual DbSet<JobExecution> JobExecution { get; set; }
        public virtual DbSet<LogScheduleAgent> LogScheduleAgent { get; set; }
    
        public virtual int SP_DOL_IMPORTAZIONE_DOMANDE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DOL_IMPORTAZIONE_DOMANDE");
        }
    }
}
