//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobExecution
    {
        public int Id { get; set; }
        public int IdJob { get; set; }
        public System.DateTime DataInizioEsecuzione { get; set; }
        public Nullable<System.DateTime> DataFineEsecuzione { get; set; }
        public string Esito { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
