//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progetto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Progetto()
        {
            this.DomandaPartecipazione = new HashSet<DomandaPartecipazione>();
        }
    
        public string CodiceEnte { get; set; }
        public string NomeEnte { get; set; }
        public string Sito { get; set; }
        public string CodiceProgetto { get; set; }
        public string TitoloProgetto { get; set; }
        public string TipoProgetto { get; set; }
        public int CodiceSede { get; set; }
        public string IndirizzoSede { get; set; }
        public string Regione { get; set; }
        public string Provincia { get; set; }
        public string Comune { get; set; }
        public string Settore { get; set; }
        public string Area { get; set; }
        public Nullable<short> NumeroPostiDisponibili { get; set; }
        public int Gruppo { get; set; }
        public string Misure { get; set; }
        public byte DurataProgettoMesi { get; set; }
        public short NumeroGiovaniMinoriOpportunità { get; set; }
        public string EsteroUE { get; set; }
        public string Tutoraggio { get; set; }
        public Nullable<System.DateTime> DataAnnullamento { get; set; }
        public Nullable<int> IDParticolaritàEntità { get; set; }
        public Nullable<int> IdProgramma { get; set; }
        public string LinkSintesi { get; set; }
        public string EnteAttuatore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DomandaPartecipazione> DomandaPartecipazione { get; set; }
        public virtual Bando Bando { get; set; }
    }
}
