'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace WS_Autenticazione
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsAutenticazioneSoap", [Namespace]:="http://tempuri.org/WSAUTENTICAZIONE/wsAutenticazione")>  _
    Partial Public Class wsAutenticazione
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EseguiAutenticazioneOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Futuro.My.MySettings.Default.Futuro_WS_Autenticazione_wsAutenticazione
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EseguiAutenticazioneCompleted As EseguiAutenticazioneCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSAUTENTICAZIONE/wsAutenticazione/EseguiAutenticazione", RequestNamespace:="http://tempuri.org/WSAUTENTICAZIONE/wsAutenticazione", ResponseNamespace:="http://tempuri.org/WSAUTENTICAZIONE/wsAutenticazione", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EseguiAutenticazione(ByVal username As String, ByVal pwd As String) As String
            Dim results() As Object = Me.Invoke("EseguiAutenticazione", New Object() {username, pwd})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EseguiAutenticazioneAsync(ByVal username As String, ByVal pwd As String)
            Me.EseguiAutenticazioneAsync(username, pwd, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EseguiAutenticazioneAsync(ByVal username As String, ByVal pwd As String, ByVal userState As Object)
            If (Me.EseguiAutenticazioneOperationCompleted Is Nothing) Then
                Me.EseguiAutenticazioneOperationCompleted = AddressOf Me.OnEseguiAutenticazioneOperationCompleted
            End If
            Me.InvokeAsync("EseguiAutenticazione", New Object() {username, pwd}, Me.EseguiAutenticazioneOperationCompleted, userState)
        End Sub
        
        Private Sub OnEseguiAutenticazioneOperationCompleted(ByVal arg As Object)
            If (Not (Me.EseguiAutenticazioneCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EseguiAutenticazioneCompleted(Me, New EseguiAutenticazioneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub EseguiAutenticazioneCompletedEventHandler(ByVal sender As Object, ByVal e As EseguiAutenticazioneCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EseguiAutenticazioneCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
