USE [master]
GO

/****** Object:  Database [unscproduzione]    Script Date: 12/08/2022 11:30:22 ******/
CREATE DATABASE [unscproduzione] 


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [unscproduzione].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [unscproduzione] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [unscproduzione] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [unscproduzione] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [unscproduzione] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [unscproduzione] SET ARITHABORT OFF 
GO

ALTER DATABASE [unscproduzione] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [unscproduzione] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [unscproduzione] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [unscproduzione] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [unscproduzione] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [unscproduzione] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [unscproduzione] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [unscproduzione] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [unscproduzione] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [unscproduzione] SET  DISABLE_BROKER 
GO

ALTER DATABASE [unscproduzione] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [unscproduzione] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [unscproduzione] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [unscproduzione] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [unscproduzione] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [unscproduzione] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [unscproduzione] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [unscproduzione] SET RECOVERY FULL 
GO

ALTER DATABASE [unscproduzione] SET  MULTI_USER 
GO

ALTER DATABASE [unscproduzione] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [unscproduzione] SET DB_CHAINING OFF 
GO

ALTER DATABASE [unscproduzione] SET  READ_WRITE 
GO


