//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Intranet/", ConfigurationName="EmailService.AnagraficaLotusSoap")]
    public interface AnagraficaLotusSoap
    {
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento codicevol dello spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/Obiettori", ReplyAction="*")]
        EmailService.ObiettoriResponse Obiettori(EmailService.ObiettoriRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/Obiettori", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.ObiettoriResponse> ObiettoriAsync(EmailService.ObiettoriRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento Denominazione dello spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/AnagrafeSiged", ReplyAction="*")]
        EmailService.AnagrafeSigedResponse AnagrafeSiged(EmailService.AnagrafeSigedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/AnagrafeSiged", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.AnagrafeSigedResponse> AnagrafeSigedAsync(EmailService.AnagrafeSigedRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento Denominazione dello spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/AnagrafeSigedWs", ReplyAction="*")]
        EmailService.AnagrafeSigedWsResponse AnagrafeSigedWs(EmailService.AnagrafeSigedWsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/AnagrafeSigedWs", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.AnagrafeSigedWsResponse> AnagrafeSigedWsAsync(EmailService.AnagrafeSigedWsRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento codicevol dello spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/Volontario", ReplyAction="*")]
        EmailService.VolontarioResponse Volontario(EmailService.VolontarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/Volontario", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.VolontarioResponse> VolontarioAsync(EmailService.VolontarioRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento codicevol dello spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/Enti", ReplyAction="*")]
        EmailService.EntiResponse Enti(EmailService.EntiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/Enti", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.EntiResponse> EntiAsync(EmailService.EntiRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento idFile dello spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/ScriviDir", ReplyAction="*")]
        EmailService.ScriviDirResponse ScriviDir(EmailService.ScriviDirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/ScriviDir", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.ScriviDirResponse> ScriviDirAsync(EmailService.ScriviDirRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento idFile dello spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/ScriviDirTest", ReplyAction="*")]
        EmailService.ScriviDirTestResponse ScriviDirTest(EmailService.ScriviDirTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/ScriviDirTest", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.ScriviDirTestResponse> ScriviDirTestAsync(EmailService.ScriviDirTestRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento pathFile dello spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/ScriviFile", ReplyAction="*")]
        EmailService.ScriviFileResponse ScriviFile(EmailService.ScriviFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/ScriviFile", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.ScriviFileResponse> ScriviFileAsync(EmailService.ScriviFileRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento pathFile dello spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/LeggiFile", ReplyAction="*")]
        EmailService.LeggiFileResponse LeggiFile(EmailService.LeggiFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/LeggiFile", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.LeggiFileResponse> LeggiFileAsync(EmailService.LeggiFileRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento pathFile dello spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/LeggiFileByte", ReplyAction="*")]
        EmailService.LeggiFileByteResponse LeggiFileByte(EmailService.LeggiFileByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/LeggiFileByte", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.LeggiFileByteResponse> LeggiFileByteAsync(EmailService.LeggiFileByteRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento indiOri dello spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/email", ReplyAction="*")]
        EmailService.emailResponse email(EmailService.emailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/email", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.emailResponse> emailAsync(EmailService.emailRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento sNomeFile dello spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/UpdateFileDoc", ReplyAction="*")]
        EmailService.UpdateFileDocResponse UpdateFileDoc(EmailService.UpdateFileDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/UpdateFileDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.UpdateFileDocResponse> UpdateFileDocAsync(EmailService.UpdateFileDocRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObiettoriRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Obiettori", Namespace="http://Intranet/", Order=0)]
        public EmailService.ObiettoriRequestBody Body;
        
        public ObiettoriRequest()
        {
        }
        
        public ObiettoriRequest(EmailService.ObiettoriRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ObiettoriRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codicevol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cognome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nome;
        
        public ObiettoriRequestBody()
        {
        }
        
        public ObiettoriRequestBody(string codicevol, string Cognome, string Nome)
        {
            this.codicevol = codicevol;
            this.Cognome = Cognome;
            this.Nome = Nome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObiettoriResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObiettoriResponse", Namespace="http://Intranet/", Order=0)]
        public EmailService.ObiettoriResponseBody Body;
        
        public ObiettoriResponse()
        {
        }
        
        public ObiettoriResponse(EmailService.ObiettoriResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ObiettoriResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObiettoriResult;
        
        public ObiettoriResponseBody()
        {
        }
        
        public ObiettoriResponseBody(string ObiettoriResult)
        {
            this.ObiettoriResult = ObiettoriResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnagrafeSigedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnagrafeSiged", Namespace="http://Intranet/", Order=0)]
        public EmailService.AnagrafeSigedRequestBody Body;
        
        public AnagrafeSigedRequest()
        {
        }
        
        public AnagrafeSigedRequest(EmailService.AnagrafeSigedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class AnagrafeSigedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Denominazione;
        
        public AnagrafeSigedRequestBody()
        {
        }
        
        public AnagrafeSigedRequestBody(string Denominazione)
        {
            this.Denominazione = Denominazione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnagrafeSigedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnagrafeSigedResponse", Namespace="http://Intranet/", Order=0)]
        public EmailService.AnagrafeSigedResponseBody Body;
        
        public AnagrafeSigedResponse()
        {
        }
        
        public AnagrafeSigedResponse(EmailService.AnagrafeSigedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class AnagrafeSigedResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnagrafeSigedResult;
        
        public AnagrafeSigedResponseBody()
        {
        }
        
        public AnagrafeSigedResponseBody(string AnagrafeSigedResult)
        {
            this.AnagrafeSigedResult = AnagrafeSigedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnagrafeSigedWsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnagrafeSigedWs", Namespace="http://Intranet/", Order=0)]
        public EmailService.AnagrafeSigedWsRequestBody Body;
        
        public AnagrafeSigedWsRequest()
        {
        }
        
        public AnagrafeSigedWsRequest(EmailService.AnagrafeSigedWsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class AnagrafeSigedWsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Denominazione;
        
        public AnagrafeSigedWsRequestBody()
        {
        }
        
        public AnagrafeSigedWsRequestBody(string Denominazione)
        {
            this.Denominazione = Denominazione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnagrafeSigedWsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnagrafeSigedWsResponse", Namespace="http://Intranet/", Order=0)]
        public EmailService.AnagrafeSigedWsResponseBody Body;
        
        public AnagrafeSigedWsResponse()
        {
        }
        
        public AnagrafeSigedWsResponse(EmailService.AnagrafeSigedWsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class AnagrafeSigedWsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnagrafeSigedWsResult;
        
        public AnagrafeSigedWsResponseBody()
        {
        }
        
        public AnagrafeSigedWsResponseBody(string AnagrafeSigedWsResult)
        {
            this.AnagrafeSigedWsResult = AnagrafeSigedWsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VolontarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Volontario", Namespace="http://Intranet/", Order=0)]
        public EmailService.VolontarioRequestBody Body;
        
        public VolontarioRequest()
        {
        }
        
        public VolontarioRequest(EmailService.VolontarioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class VolontarioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codicevol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cognome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nome;
        
        public VolontarioRequestBody()
        {
        }
        
        public VolontarioRequestBody(string codicevol, string Cognome, string Nome)
        {
            this.codicevol = codicevol;
            this.Cognome = Cognome;
            this.Nome = Nome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VolontarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VolontarioResponse", Namespace="http://Intranet/", Order=0)]
        public EmailService.VolontarioResponseBody Body;
        
        public VolontarioResponse()
        {
        }
        
        public VolontarioResponse(EmailService.VolontarioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class VolontarioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VolontarioResult;
        
        public VolontarioResponseBody()
        {
        }
        
        public VolontarioResponseBody(string VolontarioResult)
        {
            this.VolontarioResult = VolontarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntiRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Enti", Namespace="http://Intranet/", Order=0)]
        public EmailService.EntiRequestBody Body;
        
        public EntiRequest()
        {
        }
        
        public EntiRequest(EmailService.EntiRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class EntiRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codicevol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Denominazione;
        
        public EntiRequestBody()
        {
        }
        
        public EntiRequestBody(string codicevol, string Denominazione)
        {
            this.codicevol = codicevol;
            this.Denominazione = Denominazione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntiResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EntiResponse", Namespace="http://Intranet/", Order=0)]
        public EmailService.EntiResponseBody Body;
        
        public EntiResponse()
        {
        }
        
        public EntiResponse(EmailService.EntiResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class EntiResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EntiResult;
        
        public EntiResponseBody()
        {
        }
        
        public EntiResponseBody(string EntiResult)
        {
            this.EntiResult = EntiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScriviDirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScriviDir", Namespace="http://Intranet/", Order=0)]
        public EmailService.ScriviDirRequestBody Body;
        
        public ScriviDirRequest()
        {
        }
        
        public ScriviDirRequest(EmailService.ScriviDirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ScriviDirRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idFile;
        
        public ScriviDirRequestBody()
        {
        }
        
        public ScriviDirRequestBody(string idFile)
        {
            this.idFile = idFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScriviDirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScriviDirResponse", Namespace="http://Intranet/", Order=0)]
        public EmailService.ScriviDirResponseBody Body;
        
        public ScriviDirResponse()
        {
        }
        
        public ScriviDirResponse(EmailService.ScriviDirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ScriviDirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ScriviDirResult;
        
        public ScriviDirResponseBody()
        {
        }
        
        public ScriviDirResponseBody(bool ScriviDirResult)
        {
            this.ScriviDirResult = ScriviDirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScriviDirTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScriviDirTest", Namespace="http://Intranet/", Order=0)]
        public EmailService.ScriviDirTestRequestBody Body;
        
        public ScriviDirTestRequest()
        {
        }
        
        public ScriviDirTestRequest(EmailService.ScriviDirTestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ScriviDirTestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idFile;
        
        public ScriviDirTestRequestBody()
        {
        }
        
        public ScriviDirTestRequestBody(string idFile)
        {
            this.idFile = idFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScriviDirTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScriviDirTestResponse", Namespace="http://Intranet/", Order=0)]
        public EmailService.ScriviDirTestResponseBody Body;
        
        public ScriviDirTestResponse()
        {
        }
        
        public ScriviDirTestResponse(EmailService.ScriviDirTestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ScriviDirTestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ScriviDirTestResult;
        
        public ScriviDirTestResponseBody()
        {
        }
        
        public ScriviDirTestResponseBody(bool ScriviDirTestResult)
        {
            this.ScriviDirTestResult = ScriviDirTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScriviFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScriviFile", Namespace="http://Intranet/", Order=0)]
        public EmailService.ScriviFileRequestBody Body;
        
        public ScriviFileRequest()
        {
        }
        
        public ScriviFileRequest(EmailService.ScriviFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ScriviFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pathFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomeFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] byteFile;
        
        public ScriviFileRequestBody()
        {
        }
        
        public ScriviFileRequestBody(string pathFile, string nomeFile, byte[] byteFile)
        {
            this.pathFile = pathFile;
            this.nomeFile = nomeFile;
            this.byteFile = byteFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScriviFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScriviFileResponse", Namespace="http://Intranet/", Order=0)]
        public EmailService.ScriviFileResponseBody Body;
        
        public ScriviFileResponse()
        {
        }
        
        public ScriviFileResponse(EmailService.ScriviFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ScriviFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ScriviFileResult;
        
        public ScriviFileResponseBody()
        {
        }
        
        public ScriviFileResponseBody(bool ScriviFileResult)
        {
            this.ScriviFileResult = ScriviFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeggiFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeggiFile", Namespace="http://Intranet/", Order=0)]
        public EmailService.LeggiFileRequestBody Body;
        
        public LeggiFileRequest()
        {
        }
        
        public LeggiFileRequest(EmailService.LeggiFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class LeggiFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pathFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomeFile;
        
        public LeggiFileRequestBody()
        {
        }
        
        public LeggiFileRequestBody(string pathFile, string nomeFile)
        {
            this.pathFile = pathFile;
            this.nomeFile = nomeFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeggiFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeggiFileResponse", Namespace="http://Intranet/", Order=0)]
        public EmailService.LeggiFileResponseBody Body;
        
        public LeggiFileResponse()
        {
        }
        
        public LeggiFileResponse(EmailService.LeggiFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class LeggiFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LeggiFileResult;
        
        public LeggiFileResponseBody()
        {
        }
        
        public LeggiFileResponseBody(string LeggiFileResult)
        {
            this.LeggiFileResult = LeggiFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeggiFileByteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeggiFileByte", Namespace="http://Intranet/", Order=0)]
        public EmailService.LeggiFileByteRequestBody Body;
        
        public LeggiFileByteRequest()
        {
        }
        
        public LeggiFileByteRequest(EmailService.LeggiFileByteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class LeggiFileByteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pathFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomeFile;
        
        public LeggiFileByteRequestBody()
        {
        }
        
        public LeggiFileByteRequestBody(string pathFile, string nomeFile)
        {
            this.pathFile = pathFile;
            this.nomeFile = nomeFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeggiFileByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeggiFileByteResponse", Namespace="http://Intranet/", Order=0)]
        public EmailService.LeggiFileByteResponseBody Body;
        
        public LeggiFileByteResponse()
        {
        }
        
        public LeggiFileByteResponse(EmailService.LeggiFileByteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class LeggiFileByteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] LeggiFileByteResult;
        
        public LeggiFileByteResponseBody()
        {
        }
        
        public LeggiFileByteResponseBody(byte[] LeggiFileByteResult)
        {
            this.LeggiFileByteResult = LeggiFileByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class emailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="email", Namespace="http://Intranet/", Order=0)]
        public EmailService.emailRequestBody Body;
        
        public emailRequest()
        {
        }
        
        public emailRequest(EmailService.emailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class emailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string indiOri;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string indiDest;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string oggetto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string corpo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string filetosend;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool produzione;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CC;
        
        public emailRequestBody()
        {
        }
        
        public emailRequestBody(string indiOri, string indiDest, string oggetto, string corpo, string filetosend, bool produzione, string CC)
        {
            this.indiOri = indiOri;
            this.indiDest = indiDest;
            this.oggetto = oggetto;
            this.corpo = corpo;
            this.filetosend = filetosend;
            this.produzione = produzione;
            this.CC = CC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class emailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="emailResponse", Namespace="http://Intranet/", Order=0)]
        public EmailService.emailResponseBody Body;
        
        public emailResponse()
        {
        }
        
        public emailResponse(EmailService.emailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class emailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool emailResult;
        
        public emailResponseBody()
        {
        }
        
        public emailResponseBody(bool emailResult)
        {
            this.emailResult = emailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFileDocRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFileDoc", Namespace="http://Intranet/", Order=0)]
        public EmailService.UpdateFileDocRequestBody Body;
        
        public UpdateFileDocRequest()
        {
        }
        
        public UpdateFileDocRequest(EmailService.UpdateFileDocRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class UpdateFileDocRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdFileDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Statomod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sNomeFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sEstensioneFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cuser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Nuser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public byte[] bArray;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] hashAray;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool Determina;
        
        public UpdateFileDocRequestBody()
        {
        }
        
        public UpdateFileDocRequestBody(int IdFileDoc, int IDDoc, int Statomod, string sNomeFile, string sEstensioneFile, string Cuser, string Nuser, byte[] bArray, byte[] hashAray, bool Determina)
        {
            this.IdFileDoc = IdFileDoc;
            this.IDDoc = IDDoc;
            this.Statomod = Statomod;
            this.sNomeFile = sNomeFile;
            this.sEstensioneFile = sEstensioneFile;
            this.Cuser = Cuser;
            this.Nuser = Nuser;
            this.bArray = bArray;
            this.hashAray = hashAray;
            this.Determina = Determina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFileDocResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFileDocResponse", Namespace="http://Intranet/", Order=0)]
        public EmailService.UpdateFileDocResponseBody Body;
        
        public UpdateFileDocResponse()
        {
        }
        
        public UpdateFileDocResponse(EmailService.UpdateFileDocResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class UpdateFileDocResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateFileDocResult;
        
        public UpdateFileDocResponseBody()
        {
        }
        
        public UpdateFileDocResponseBody(bool UpdateFileDocResult)
        {
            this.UpdateFileDocResult = UpdateFileDocResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface AnagraficaLotusSoapChannel : EmailService.AnagraficaLotusSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AnagraficaLotusSoapClient : System.ServiceModel.ClientBase<EmailService.AnagraficaLotusSoap>, EmailService.AnagraficaLotusSoap
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AnagraficaLotusSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AnagraficaLotusSoapClient.GetBindingForEndpoint(endpointConfiguration), AnagraficaLotusSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AnagraficaLotusSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AnagraficaLotusSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AnagraficaLotusSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AnagraficaLotusSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AnagraficaLotusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailService.ObiettoriResponse EmailService.AnagraficaLotusSoap.Obiettori(EmailService.ObiettoriRequest request)
        {
            return base.Channel.Obiettori(request);
        }
        
        public string Obiettori(string codicevol, string Cognome, string Nome)
        {
            EmailService.ObiettoriRequest inValue = new EmailService.ObiettoriRequest();
            inValue.Body = new EmailService.ObiettoriRequestBody();
            inValue.Body.codicevol = codicevol;
            inValue.Body.Cognome = Cognome;
            inValue.Body.Nome = Nome;
            EmailService.ObiettoriResponse retVal = ((EmailService.AnagraficaLotusSoap)(this)).Obiettori(inValue);
            return retVal.Body.ObiettoriResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.ObiettoriResponse> EmailService.AnagraficaLotusSoap.ObiettoriAsync(EmailService.ObiettoriRequest request)
        {
            return base.Channel.ObiettoriAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.ObiettoriResponse> ObiettoriAsync(string codicevol, string Cognome, string Nome)
        {
            EmailService.ObiettoriRequest inValue = new EmailService.ObiettoriRequest();
            inValue.Body = new EmailService.ObiettoriRequestBody();
            inValue.Body.codicevol = codicevol;
            inValue.Body.Cognome = Cognome;
            inValue.Body.Nome = Nome;
            return ((EmailService.AnagraficaLotusSoap)(this)).ObiettoriAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailService.AnagrafeSigedResponse EmailService.AnagraficaLotusSoap.AnagrafeSiged(EmailService.AnagrafeSigedRequest request)
        {
            return base.Channel.AnagrafeSiged(request);
        }
        
        public string AnagrafeSiged(string Denominazione)
        {
            EmailService.AnagrafeSigedRequest inValue = new EmailService.AnagrafeSigedRequest();
            inValue.Body = new EmailService.AnagrafeSigedRequestBody();
            inValue.Body.Denominazione = Denominazione;
            EmailService.AnagrafeSigedResponse retVal = ((EmailService.AnagraficaLotusSoap)(this)).AnagrafeSiged(inValue);
            return retVal.Body.AnagrafeSigedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.AnagrafeSigedResponse> EmailService.AnagraficaLotusSoap.AnagrafeSigedAsync(EmailService.AnagrafeSigedRequest request)
        {
            return base.Channel.AnagrafeSigedAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.AnagrafeSigedResponse> AnagrafeSigedAsync(string Denominazione)
        {
            EmailService.AnagrafeSigedRequest inValue = new EmailService.AnagrafeSigedRequest();
            inValue.Body = new EmailService.AnagrafeSigedRequestBody();
            inValue.Body.Denominazione = Denominazione;
            return ((EmailService.AnagraficaLotusSoap)(this)).AnagrafeSigedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailService.AnagrafeSigedWsResponse EmailService.AnagraficaLotusSoap.AnagrafeSigedWs(EmailService.AnagrafeSigedWsRequest request)
        {
            return base.Channel.AnagrafeSigedWs(request);
        }
        
        public string AnagrafeSigedWs(string Denominazione)
        {
            EmailService.AnagrafeSigedWsRequest inValue = new EmailService.AnagrafeSigedWsRequest();
            inValue.Body = new EmailService.AnagrafeSigedWsRequestBody();
            inValue.Body.Denominazione = Denominazione;
            EmailService.AnagrafeSigedWsResponse retVal = ((EmailService.AnagraficaLotusSoap)(this)).AnagrafeSigedWs(inValue);
            return retVal.Body.AnagrafeSigedWsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.AnagrafeSigedWsResponse> EmailService.AnagraficaLotusSoap.AnagrafeSigedWsAsync(EmailService.AnagrafeSigedWsRequest request)
        {
            return base.Channel.AnagrafeSigedWsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.AnagrafeSigedWsResponse> AnagrafeSigedWsAsync(string Denominazione)
        {
            EmailService.AnagrafeSigedWsRequest inValue = new EmailService.AnagrafeSigedWsRequest();
            inValue.Body = new EmailService.AnagrafeSigedWsRequestBody();
            inValue.Body.Denominazione = Denominazione;
            return ((EmailService.AnagraficaLotusSoap)(this)).AnagrafeSigedWsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailService.VolontarioResponse EmailService.AnagraficaLotusSoap.Volontario(EmailService.VolontarioRequest request)
        {
            return base.Channel.Volontario(request);
        }
        
        public string Volontario(string codicevol, string Cognome, string Nome)
        {
            EmailService.VolontarioRequest inValue = new EmailService.VolontarioRequest();
            inValue.Body = new EmailService.VolontarioRequestBody();
            inValue.Body.codicevol = codicevol;
            inValue.Body.Cognome = Cognome;
            inValue.Body.Nome = Nome;
            EmailService.VolontarioResponse retVal = ((EmailService.AnagraficaLotusSoap)(this)).Volontario(inValue);
            return retVal.Body.VolontarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.VolontarioResponse> EmailService.AnagraficaLotusSoap.VolontarioAsync(EmailService.VolontarioRequest request)
        {
            return base.Channel.VolontarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.VolontarioResponse> VolontarioAsync(string codicevol, string Cognome, string Nome)
        {
            EmailService.VolontarioRequest inValue = new EmailService.VolontarioRequest();
            inValue.Body = new EmailService.VolontarioRequestBody();
            inValue.Body.codicevol = codicevol;
            inValue.Body.Cognome = Cognome;
            inValue.Body.Nome = Nome;
            return ((EmailService.AnagraficaLotusSoap)(this)).VolontarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailService.EntiResponse EmailService.AnagraficaLotusSoap.Enti(EmailService.EntiRequest request)
        {
            return base.Channel.Enti(request);
        }
        
        public string Enti(string codicevol, string Denominazione)
        {
            EmailService.EntiRequest inValue = new EmailService.EntiRequest();
            inValue.Body = new EmailService.EntiRequestBody();
            inValue.Body.codicevol = codicevol;
            inValue.Body.Denominazione = Denominazione;
            EmailService.EntiResponse retVal = ((EmailService.AnagraficaLotusSoap)(this)).Enti(inValue);
            return retVal.Body.EntiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.EntiResponse> EmailService.AnagraficaLotusSoap.EntiAsync(EmailService.EntiRequest request)
        {
            return base.Channel.EntiAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.EntiResponse> EntiAsync(string codicevol, string Denominazione)
        {
            EmailService.EntiRequest inValue = new EmailService.EntiRequest();
            inValue.Body = new EmailService.EntiRequestBody();
            inValue.Body.codicevol = codicevol;
            inValue.Body.Denominazione = Denominazione;
            return ((EmailService.AnagraficaLotusSoap)(this)).EntiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailService.ScriviDirResponse EmailService.AnagraficaLotusSoap.ScriviDir(EmailService.ScriviDirRequest request)
        {
            return base.Channel.ScriviDir(request);
        }
        
        public bool ScriviDir(string idFile)
        {
            EmailService.ScriviDirRequest inValue = new EmailService.ScriviDirRequest();
            inValue.Body = new EmailService.ScriviDirRequestBody();
            inValue.Body.idFile = idFile;
            EmailService.ScriviDirResponse retVal = ((EmailService.AnagraficaLotusSoap)(this)).ScriviDir(inValue);
            return retVal.Body.ScriviDirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.ScriviDirResponse> EmailService.AnagraficaLotusSoap.ScriviDirAsync(EmailService.ScriviDirRequest request)
        {
            return base.Channel.ScriviDirAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.ScriviDirResponse> ScriviDirAsync(string idFile)
        {
            EmailService.ScriviDirRequest inValue = new EmailService.ScriviDirRequest();
            inValue.Body = new EmailService.ScriviDirRequestBody();
            inValue.Body.idFile = idFile;
            return ((EmailService.AnagraficaLotusSoap)(this)).ScriviDirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailService.ScriviDirTestResponse EmailService.AnagraficaLotusSoap.ScriviDirTest(EmailService.ScriviDirTestRequest request)
        {
            return base.Channel.ScriviDirTest(request);
        }
        
        public bool ScriviDirTest(string idFile)
        {
            EmailService.ScriviDirTestRequest inValue = new EmailService.ScriviDirTestRequest();
            inValue.Body = new EmailService.ScriviDirTestRequestBody();
            inValue.Body.idFile = idFile;
            EmailService.ScriviDirTestResponse retVal = ((EmailService.AnagraficaLotusSoap)(this)).ScriviDirTest(inValue);
            return retVal.Body.ScriviDirTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.ScriviDirTestResponse> EmailService.AnagraficaLotusSoap.ScriviDirTestAsync(EmailService.ScriviDirTestRequest request)
        {
            return base.Channel.ScriviDirTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.ScriviDirTestResponse> ScriviDirTestAsync(string idFile)
        {
            EmailService.ScriviDirTestRequest inValue = new EmailService.ScriviDirTestRequest();
            inValue.Body = new EmailService.ScriviDirTestRequestBody();
            inValue.Body.idFile = idFile;
            return ((EmailService.AnagraficaLotusSoap)(this)).ScriviDirTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailService.ScriviFileResponse EmailService.AnagraficaLotusSoap.ScriviFile(EmailService.ScriviFileRequest request)
        {
            return base.Channel.ScriviFile(request);
        }
        
        public bool ScriviFile(string pathFile, string nomeFile, byte[] byteFile)
        {
            EmailService.ScriviFileRequest inValue = new EmailService.ScriviFileRequest();
            inValue.Body = new EmailService.ScriviFileRequestBody();
            inValue.Body.pathFile = pathFile;
            inValue.Body.nomeFile = nomeFile;
            inValue.Body.byteFile = byteFile;
            EmailService.ScriviFileResponse retVal = ((EmailService.AnagraficaLotusSoap)(this)).ScriviFile(inValue);
            return retVal.Body.ScriviFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.ScriviFileResponse> EmailService.AnagraficaLotusSoap.ScriviFileAsync(EmailService.ScriviFileRequest request)
        {
            return base.Channel.ScriviFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.ScriviFileResponse> ScriviFileAsync(string pathFile, string nomeFile, byte[] byteFile)
        {
            EmailService.ScriviFileRequest inValue = new EmailService.ScriviFileRequest();
            inValue.Body = new EmailService.ScriviFileRequestBody();
            inValue.Body.pathFile = pathFile;
            inValue.Body.nomeFile = nomeFile;
            inValue.Body.byteFile = byteFile;
            return ((EmailService.AnagraficaLotusSoap)(this)).ScriviFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailService.LeggiFileResponse EmailService.AnagraficaLotusSoap.LeggiFile(EmailService.LeggiFileRequest request)
        {
            return base.Channel.LeggiFile(request);
        }
        
        public string LeggiFile(string pathFile, string nomeFile)
        {
            EmailService.LeggiFileRequest inValue = new EmailService.LeggiFileRequest();
            inValue.Body = new EmailService.LeggiFileRequestBody();
            inValue.Body.pathFile = pathFile;
            inValue.Body.nomeFile = nomeFile;
            EmailService.LeggiFileResponse retVal = ((EmailService.AnagraficaLotusSoap)(this)).LeggiFile(inValue);
            return retVal.Body.LeggiFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.LeggiFileResponse> EmailService.AnagraficaLotusSoap.LeggiFileAsync(EmailService.LeggiFileRequest request)
        {
            return base.Channel.LeggiFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.LeggiFileResponse> LeggiFileAsync(string pathFile, string nomeFile)
        {
            EmailService.LeggiFileRequest inValue = new EmailService.LeggiFileRequest();
            inValue.Body = new EmailService.LeggiFileRequestBody();
            inValue.Body.pathFile = pathFile;
            inValue.Body.nomeFile = nomeFile;
            return ((EmailService.AnagraficaLotusSoap)(this)).LeggiFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailService.LeggiFileByteResponse EmailService.AnagraficaLotusSoap.LeggiFileByte(EmailService.LeggiFileByteRequest request)
        {
            return base.Channel.LeggiFileByte(request);
        }
        
        public byte[] LeggiFileByte(string pathFile, string nomeFile)
        {
            EmailService.LeggiFileByteRequest inValue = new EmailService.LeggiFileByteRequest();
            inValue.Body = new EmailService.LeggiFileByteRequestBody();
            inValue.Body.pathFile = pathFile;
            inValue.Body.nomeFile = nomeFile;
            EmailService.LeggiFileByteResponse retVal = ((EmailService.AnagraficaLotusSoap)(this)).LeggiFileByte(inValue);
            return retVal.Body.LeggiFileByteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.LeggiFileByteResponse> EmailService.AnagraficaLotusSoap.LeggiFileByteAsync(EmailService.LeggiFileByteRequest request)
        {
            return base.Channel.LeggiFileByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.LeggiFileByteResponse> LeggiFileByteAsync(string pathFile, string nomeFile)
        {
            EmailService.LeggiFileByteRequest inValue = new EmailService.LeggiFileByteRequest();
            inValue.Body = new EmailService.LeggiFileByteRequestBody();
            inValue.Body.pathFile = pathFile;
            inValue.Body.nomeFile = nomeFile;
            return ((EmailService.AnagraficaLotusSoap)(this)).LeggiFileByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailService.emailResponse EmailService.AnagraficaLotusSoap.email(EmailService.emailRequest request)
        {
            return base.Channel.email(request);
        }
        
        public bool email(string indiOri, string indiDest, string oggetto, string corpo, string filetosend, bool produzione, string CC)
        {
            EmailService.emailRequest inValue = new EmailService.emailRequest();
            inValue.Body = new EmailService.emailRequestBody();
            inValue.Body.indiOri = indiOri;
            inValue.Body.indiDest = indiDest;
            inValue.Body.oggetto = oggetto;
            inValue.Body.corpo = corpo;
            inValue.Body.filetosend = filetosend;
            inValue.Body.produzione = produzione;
            inValue.Body.CC = CC;
            EmailService.emailResponse retVal = ((EmailService.AnagraficaLotusSoap)(this)).email(inValue);
            return retVal.Body.emailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.emailResponse> EmailService.AnagraficaLotusSoap.emailAsync(EmailService.emailRequest request)
        {
            return base.Channel.emailAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.emailResponse> emailAsync(string indiOri, string indiDest, string oggetto, string corpo, string filetosend, bool produzione, string CC)
        {
            EmailService.emailRequest inValue = new EmailService.emailRequest();
            inValue.Body = new EmailService.emailRequestBody();
            inValue.Body.indiOri = indiOri;
            inValue.Body.indiDest = indiDest;
            inValue.Body.oggetto = oggetto;
            inValue.Body.corpo = corpo;
            inValue.Body.filetosend = filetosend;
            inValue.Body.produzione = produzione;
            inValue.Body.CC = CC;
            return ((EmailService.AnagraficaLotusSoap)(this)).emailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailService.UpdateFileDocResponse EmailService.AnagraficaLotusSoap.UpdateFileDoc(EmailService.UpdateFileDocRequest request)
        {
            return base.Channel.UpdateFileDoc(request);
        }
        
        public bool UpdateFileDoc(int IdFileDoc, int IDDoc, int Statomod, string sNomeFile, string sEstensioneFile, string Cuser, string Nuser, byte[] bArray, byte[] hashAray, bool Determina)
        {
            EmailService.UpdateFileDocRequest inValue = new EmailService.UpdateFileDocRequest();
            inValue.Body = new EmailService.UpdateFileDocRequestBody();
            inValue.Body.IdFileDoc = IdFileDoc;
            inValue.Body.IDDoc = IDDoc;
            inValue.Body.Statomod = Statomod;
            inValue.Body.sNomeFile = sNomeFile;
            inValue.Body.sEstensioneFile = sEstensioneFile;
            inValue.Body.Cuser = Cuser;
            inValue.Body.Nuser = Nuser;
            inValue.Body.bArray = bArray;
            inValue.Body.hashAray = hashAray;
            inValue.Body.Determina = Determina;
            EmailService.UpdateFileDocResponse retVal = ((EmailService.AnagraficaLotusSoap)(this)).UpdateFileDoc(inValue);
            return retVal.Body.UpdateFileDocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.UpdateFileDocResponse> EmailService.AnagraficaLotusSoap.UpdateFileDocAsync(EmailService.UpdateFileDocRequest request)
        {
            return base.Channel.UpdateFileDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.UpdateFileDocResponse> UpdateFileDocAsync(int IdFileDoc, int IDDoc, int Statomod, string sNomeFile, string sEstensioneFile, string Cuser, string Nuser, byte[] bArray, byte[] hashAray, bool Determina)
        {
            EmailService.UpdateFileDocRequest inValue = new EmailService.UpdateFileDocRequest();
            inValue.Body = new EmailService.UpdateFileDocRequestBody();
            inValue.Body.IdFileDoc = IdFileDoc;
            inValue.Body.IDDoc = IDDoc;
            inValue.Body.Statomod = Statomod;
            inValue.Body.sNomeFile = sNomeFile;
            inValue.Body.sEstensioneFile = sEstensioneFile;
            inValue.Body.Cuser = Cuser;
            inValue.Body.Nuser = Nuser;
            inValue.Body.bArray = bArray;
            inValue.Body.hashAray = hashAray;
            inValue.Body.Determina = Determina;
            return ((EmailService.AnagraficaLotusSoap)(this)).UpdateFileDocAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AnagraficaLotusSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AnagraficaLotusSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AnagraficaLotusSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.212/WebServiceLotus/AnagrafeLotus.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AnagraficaLotusSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.212/WebServiceLotus/AnagrafeLotus.asmx");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AnagraficaLotusSoap,
            
            AnagraficaLotusSoap12,
        }
    }
}
