'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WfrmRiepilogoAntimafia

	'''<summary>
	'''ToolkitScriptManager1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ToolkitScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager

	'''<summary>
	'''msgErrore control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents msgErrore As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''msgInfo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents msgInfo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''msgConferma control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents msgConferma As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''dtgElencoDocumenti control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dtgElencoDocumenti As Global.System.Web.UI.WebControls.DataGrid

	'''<summary>
	'''cmdChiudi control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cmdChiudi As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''popUpDichiarazioni control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents popUpDichiarazioni As Global.AjaxControlToolkit.ModalPopupExtender

	'''<summary>
	'''hfDichiarazioni control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hfDichiarazioni As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''pnlDichiarazioni control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlDichiarazioni As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblErroreApriFaseAntimafia control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErroreApriFaseAntimafia As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''dtgDichiarazioni control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dtgDichiarazioni As Global.System.Web.UI.WebControls.DataGrid

	'''<summary>
	'''btnCloseDichiarazioni control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCloseDichiarazioni As Global.System.Web.UI.WebControls.Button
End Class
