<%@ Page Title="Home page" Language="vb" MasterPageFile="~/SiteNew.Master" AutoEventWireup="false" CodeBehind="WfrmMain.aspx.vb" Inherits="Futuro._WfrmMain" %>
    
<asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">

</asp:Content>
<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">
    <fieldset class="ContornoPagina">
       <asp:Label ID="lblNoSpid" runat="server" AssociatedControlID="" Text="">
           <h3 style="color: red;"><i>Attenzione: le funzioni di adeguamento dell'iscrizione all'Albo e quelle di gestione e presentazione di programmi e progetti
               sono disponibili solo effettuando l'accesso tramite SPID
               </i></h3>
           <br /><br />
       </asp:Label>
<legend>Pagina di Benvenuto</legend>

    <h3>
       <asp:Label ID="lblDenominazione" runat="server" AssociatedControlID="" Text=""></asp:Label>
    </h3>
    <br />
    <h3>
    <asp:Label ID="lblCodice" runat="server" AssociatedControlID="" Text=""></asp:Label>
    </h3>
    <br />
   <h3>
   <asp:Label ID="lblCompetenza" AssociatedControlID="" runat="server" Text=""></asp:Label>
   </h3>
   <br />
    <p>
       <asp:Label ID="lblChiso"  AssociatedControlID=""  CssClass="msgErrore" runat="server" Text=""></asp:Label>
        
    </p>
   
            <div>
                <% Call CaricaBoxInfoAdeguamentoAntimafia()%>
            </div>

    <fieldset class="ContornoPagina">
    <legend style="text-align:center;">NEWS</legend>
    
    
    <p>
        <asp:GridView ID="GridViewNew" runat="server"  AutoGenerateColumns="False" 
            AutoGenerateEditButton="False" 
            AutoGenerateDeleteButton="False" 
  DataKeyNames="IdComunicazione" AllowPaging="True" PageSize="5">

  
                
              <Columns>
                <asp:BoundField DataField="IdComunicazione" HeaderText="" SortExpression="IdComunicazione" Visible="False" />
                <asp:BoundField DataField="DataComunicazione" ItemStyle-Width="15%" 
                      HeaderText="Data" SortExpression="DataComunicazione" ReadOnly="true" >
<ItemStyle Width="15%"></ItemStyle>
                  </asp:BoundField>
                <asp:BoundField DataField="Testo" HtmlEncode="false" HeaderText="Notizie" 
                      ItemStyle-Width="85%" SortExpression="Testo" >
<ItemStyle Width="85%"></ItemStyle>
                  </asp:BoundField>
                <asp:BoundField DataField="Visibile" HeaderText="" SortExpression="Visibile" Visible="False" />
            </Columns>
              <PagerStyle HorizontalAlign="Center" />
        </asp:GridView>
        </p>
 </fieldset>

    <br />
           <p style="text-align:center">
           <%If Session("Sistema") = "Futuro" Then%>
<%--                        <img alt="Logo Unione Europea" src="Images/Logo-ue_blu_medium.png" />
               <img alt="Logo Garanzia Giovani" src="Images/logoGaranziaGiovani_medium.png" />
               <img alt="Logo Presidenza del Consiglio dei Ministri Dipartimento della Gioventù e del Servizio Civile Nazionale" src="Images/logo-presidenza_medium.png" />--%>
                        <%Else%>
                          <img  alt="Logo Dipartimento per le politiche giovanili e il Servizio civile universale" src="Images/logo-presidenza_medium.png" />

                        <%End If%>

           </p>
  </fieldset>
</asp:Content>
