USE [master]
GO

/****** Object:  Database [DomandaOnline]    Script Date: 12/08/2022 13:21:09 ******/
CREATE DATABASE [DomandaOnline]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DomandaOnline', FILENAME = N'E:\DATA\DomandaOnline.mdf' , SIZE = 367001600KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10485760KB )
 LOG ON 
( NAME = N'DomandaOnline_log', FILENAME = N'E:\LOG\DomandaOnline_log.ldf' , SIZE = 73408512KB , MAXSIZE = 2048GB , FILEGROWTH = 5242880KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DomandaOnline].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DomandaOnline] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DomandaOnline] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DomandaOnline] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DomandaOnline] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DomandaOnline] SET ARITHABORT OFF 
GO

ALTER DATABASE [DomandaOnline] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DomandaOnline] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DomandaOnline] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DomandaOnline] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DomandaOnline] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DomandaOnline] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DomandaOnline] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DomandaOnline] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DomandaOnline] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DomandaOnline] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DomandaOnline] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DomandaOnline] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DomandaOnline] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DomandaOnline] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DomandaOnline] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DomandaOnline] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DomandaOnline] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DomandaOnline] SET RECOVERY FULL 
GO

ALTER DATABASE [DomandaOnline] SET  MULTI_USER 
GO

ALTER DATABASE [DomandaOnline] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DomandaOnline] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DomandaOnline] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DomandaOnline] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DomandaOnline] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DomandaOnline] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DomandaOnline] SET  READ_WRITE 
GO


