'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace GetCUVolontari
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Volontario", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Volontario
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdCudField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdVolField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StrPWDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StrUserNameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCud() As Integer
            Get
                Return Me.IdCudField
            End Get
            Set
                If (Me.IdCudField.Equals(value) <> true) Then
                    Me.IdCudField = value
                    Me.RaisePropertyChanged("IdCud")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdVol() As Integer
            Get
                Return Me.IdVolField
            End Get
            Set
                If (Me.IdVolField.Equals(value) <> true) Then
                    Me.IdVolField = value
                    Me.RaisePropertyChanged("IdVol")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StrPWD() As String
            Get
                Return Me.StrPWDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StrPWDField, value) <> true) Then
                    Me.StrPWDField = value
                    Me.RaisePropertyChanged("StrPWD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StrUserName() As String
            Get
                Return Me.StrUserNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StrUserNameField, value) <> true) Then
                    Me.StrUserNameField = value
                    Me.RaisePropertyChanged("StrUserName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="GetCUVolontari.ICUService")>  _
    Public Interface ICUService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICUService/GetCUVol", ReplyAction:="http://tempuri.org/ICUService/GetCUVolResponse")>  _
        Function GetCUVol(ByVal volontario As GetCUVolontari.Volontario) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICUService/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/ICUService/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal volontario As GetCUVolontari.Volontario) As GetCUVolontari.Volontario
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICUServiceChannel
        Inherits GetCUVolontari.ICUService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CUServiceClient
        Inherits System.ServiceModel.ClientBase(Of GetCUVolontari.ICUService)
        Implements GetCUVolontari.ICUService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetCUVol(ByVal volontario As GetCUVolontari.Volontario) As String Implements GetCUVolontari.ICUService.GetCUVol
            Return MyBase.Channel.GetCUVol(volontario)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal volontario As GetCUVolontari.Volontario) As GetCUVolontari.Volontario Implements GetCUVolontari.ICUService.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(volontario)
        End Function
    End Class
End Namespace
