USE [master]
GO

/****** Object:  Database [Registrazione]    Script Date: 12/08/2022 12:20:14 ******/
CREATE DATABASE [Registrazione]

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Registrazione].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Registrazione] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Registrazione] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Registrazione] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Registrazione] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Registrazione] SET ARITHABORT OFF 
GO

ALTER DATABASE [Registrazione] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Registrazione] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Registrazione] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Registrazione] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Registrazione] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Registrazione] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Registrazione] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Registrazione] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Registrazione] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Registrazione] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Registrazione] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Registrazione] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Registrazione] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Registrazione] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Registrazione] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Registrazione] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Registrazione] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Registrazione] SET RECOVERY FULL 
GO

ALTER DATABASE [Registrazione] SET  MULTI_USER 
GO

ALTER DATABASE [Registrazione] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Registrazione] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Registrazione] SET  READ_WRITE 
GO


