IF NOT EXISTS(
	SELECT *
	FROM   INFORMATION_SCHEMA.COLUMNS
	WHERE  TABLE_NAME = 'SUSCN_DOL_PROGETTI_DISPONIBILI'
					 AND COLUMN_NAME = 'NumeroDomande'
)
BEGIN
	ALTER TABLE SUSCN_DOL_PROGETTI_DISPONIBILI 
	ADD NumeroDomande INT
END

