//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomandeOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bando
    {
        public Bando()
        {
            this.Progetti = new HashSet<Progetto>();
        }
    
        public int Gruppo { get; set; }
        public string Descrizione { get; set; }
        public string Scadenza { get; set; }
        public System.DateTime DataScadenza { get; set; }
        public Nullable<System.DateTime> DataScadenzaGraduatorie { get; set; }
        public Nullable<int> GiorniPostScadenza { get; set; }
        public bool? Programmi { get; set; }
        public Nullable<DateTime> DataFineAnnullamento { get; set; }

        public virtual ICollection<Progetto> Progetti { get; set; }
    }
}
