//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomandeOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comune
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CodiceCatastale { get; set; }
        public Nullable<int> IdPRovincia { get; set; }
    
        public virtual Provincia Provincia { get; set; }
    }
}
