//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomandeOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomandaVariata
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DataPresentazione { get; set; }
        public Nullable<System.DateTime> DataCaricamento { get; set; }
        public string Email { get; set; }
        public string CodiceFiscale { get; set; }
        public byte[] FileVecchio { get; set; }
        public Nullable<int> IdDomanda { get; set; }
        public Nullable<System.DateTime> DataInvioEmail { get; set; }
        public string TextOld { get; set; }
        public string TextNew { get; set; }
        public Nullable<bool> Dichiarazione { get; set; }
    }
}
