//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomandeOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinoreOpportunita
    {
        public const int BASSA_SCOLARIZZAZIONE = 3;
        public const int DIFFICOLTA_ECONOMICHE = 4;
        public const int DISABILITA = 5;
        public const int CARE_LEAVERS = 7;
        public const int TEMPORANEA_FRAGILITA = 8;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MinoreOpportunita()
        {
            this.Progetti = new HashSet<Progetto>();
        }
    
        public int IDParticolarità { get; set; }
        public string Descrizione { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Progetto> Progetti { get; set; }
    }
}
