//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomandeOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programma()
        {
            this.Obiettivi = new HashSet<Obiettivo>();
            this.Progetti = new HashSet<Progetto>();
        }
    
        public int IdProgramma { get; set; }
        public string Titolo { get; set; }
        public int IdAmbitoAzione { get; set; }
        public Nullable<int> IdTipoGG { get; set; }
        public Nullable<bool> IsDigitale { get; set; }
        public Nullable<bool> IsAmbientale { get; set; }
        public Nullable<bool> IsAutofinanziato { get; set; }


        public virtual GaranziaGiovani GaranziaGiovane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obiettivo> Obiettivi { get; set; }
        public virtual Ambito Ambito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Progetto> Progetti { get; set; }
    }
}
