//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomandeOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitiGaranziaGiovani
    {
        public string TipoGG { get; set; }
        public Nullable<int> IdRegione { get; set; }
        public Nullable<int> IdProvincia { get; set; }
    
        public virtual Provincia Provincia { get; set; }
        public virtual Regione Regione { get; set; }
    }
}
