//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomandeOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RichiestaCredenziali
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DataRichiesta { get; set; }
        public Nullable<int> IdStato { get; set; }
        public Nullable<System.DateTime> DataApprovazione { get; set; }
        public string UtenteApprovazione { get; set; }
        public string NoteApprovazione { get; set; }
        public string UtenteAnnullamento { get; set; }
        public string NoteAnnullamento { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string CodiceGenere { get; set; }
        public Nullable<System.DateTime> DataNascita { get; set; }
        public string LuogoNascita { get; set; }
        public Nullable<int> IdNazioneNascita { get; set; }
        public string CodiceFiscale { get; set; }
        public Nullable<int> IdNazioneCittadinanza { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public byte[] Allegato { get; set; }
        public Nullable<System.DateTime> DataAnnullamento { get; set; }
    
        public virtual Genere Genere { get; set; }
        public virtual Nazione Cittadinanza { get; set; }
        public virtual Nazione NazioneNascita { get; set; }
        public virtual StatoRichiestaCredenziali Stato { get; set; }
    }
}
