//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomandeOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolontarioServizio
    {
        public string CodiceFiscale { get; set; }
        public System.DateTime DataInizioServizio { get; set; }
        public System.DateTime DataFineServizio { get; set; }
        public string TipoServizio { get; set; }
    }
}
