//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtocolloNewService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documento", Namespace="http://schemas.datacontract.org/2004/07/WcfPostProtocolloNew")]
    public partial class Documento : object
    {
        
        private int CodDocField;
        
        private System.DateTime DataprotField;
        
        private string OggettoField;
        
        private string ProtNumField;
        
        private int TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodDoc
        {
            get
            {
                return this.CodDocField;
            }
            set
            {
                this.CodDocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dataprot
        {
            get
            {
                return this.DataprotField;
            }
            set
            {
                this.DataprotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Oggetto
        {
            get
            {
                return this.OggettoField;
            }
            set
            {
                this.OggettoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProtNum
        {
            get
            {
                return this.ProtNumField;
            }
            set
            {
                this.ProtNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utente", Namespace="http://schemas.datacontract.org/2004/07/WcfPostProtocolloNew")]
    public partial class Utente : object
    {
        
        private string CognomeField;
        
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome
        {
            get
            {
                return this.CognomeField;
            }
            set
            {
                this.CognomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Destinatario", Namespace="http://schemas.datacontract.org/2004/07/WcfPostProtocolloNew")]
    public partial class Destinatario : object
    {
        
        private string CodiceDestField;
        
        private string EmailPECdestField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceDest
        {
            get
            {
                return this.CodiceDestField;
            }
            set
            {
                this.CodiceDestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailPECdest
        {
            get
            {
                return this.EmailPECdestField;
            }
            set
            {
                this.EmailPECdestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ente", Namespace="http://schemas.datacontract.org/2004/07/WcfPostProtocolloNew")]
    public partial class Ente : object
    {
        
        private string CodevscField;
        
        private string EnteEvscField;
        
        private bool EntescField;
        
        private int EvscField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codevsc
        {
            get
            {
                return this.CodevscField;
            }
            set
            {
                this.CodevscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnteEvsc
        {
            get
            {
                return this.EnteEvscField;
            }
            set
            {
                this.EnteEvscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Entesc
        {
            get
            {
                return this.EntescField;
            }
            set
            {
                this.EntescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Evsc
        {
            get
            {
                return this.EvscField;
            }
            set
            {
                this.EvscField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Allegati", Namespace="http://schemas.datacontract.org/2004/07/WcfPostProtocolloNew")]
    public partial class Allegati : object
    {
        
        private string[] FileallegatiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Fileallegati
        {
            get
            {
                return this.FileallegatiField;
            }
            set
            {
                this.FileallegatiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fascicolo", Namespace="http://schemas.datacontract.org/2004/07/WcfPostProtocolloNew")]
    public partial class Fascicolo : object
    {
        
        private string AooPField;
        
        private string CategoriaField;
        
        private string CodfascPField;
        
        private string CodiceDefaultField;
        
        private string DataAperturaField;
        
        private string DescrFascPField;
        
        private string RiferimentoField;
        
        private string StatoField;
        
        private string TitolarioPField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AooP
        {
            get
            {
                return this.AooPField;
            }
            set
            {
                this.AooPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodfascP
        {
            get
            {
                return this.CodfascPField;
            }
            set
            {
                this.CodfascPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceDefault
        {
            get
            {
                return this.CodiceDefaultField;
            }
            set
            {
                this.CodiceDefaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataApertura
        {
            get
            {
                return this.DataAperturaField;
            }
            set
            {
                this.DataAperturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescrFascP
        {
            get
            {
                return this.DescrFascPField;
            }
            set
            {
                this.DescrFascPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Riferimento
        {
            get
            {
                return this.RiferimentoField;
            }
            set
            {
                this.RiferimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stato
        {
            get
            {
                return this.StatoField;
            }
            set
            {
                this.StatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitolarioP
        {
            get
            {
                return this.TitolarioPField;
            }
            set
            {
                this.TitolarioPField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileToSend", Namespace="http://schemas.datacontract.org/2004/07/WcfPostProtocolloNew")]
    public partial class FileToSend : object
    {
        
        private string DescrFascField;
        
        private string FileB64Field;
        
        private string FileToSendLocalField;
        
        private string NomeFileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescrFasc
        {
            get
            {
                return this.DescrFascField;
            }
            set
            {
                this.DescrFascField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileB64
        {
            get
            {
                return this.FileB64Field;
            }
            set
            {
                this.FileB64Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileToSendLocal
        {
            get
            {
                return this.FileToSendLocalField;
            }
            set
            {
                this.FileToSendLocalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeFile
        {
            get
            {
                return this.NomeFileField;
            }
            set
            {
                this.NomeFileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewProtocollo", Namespace="http://schemas.datacontract.org/2004/07/WcfPostProtocolloNew")]
    public partial class NewProtocollo : object
    {
        
        private string DataProtField;
        
        private string NumeroProtField;
        
        private string StatoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataProt
        {
            get
            {
                return this.DataProtField;
            }
            set
            {
                this.DataProtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroProt
        {
            get
            {
                return this.NumeroProtField;
            }
            set
            {
                this.NumeroProtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stato
        {
            get
            {
                return this.StatoField;
            }
            set
            {
                this.StatoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Assegnatari", Namespace="http://schemas.datacontract.org/2004/07/WcfPostProtocolloNew")]
    public partial class Assegnatari : object
    {
        
        private string[] ServAssegnatariField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ServAssegnatari
        {
            get
            {
                return this.ServAssegnatariField;
            }
            set
            {
                this.ServAssegnatariField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProtocolloNewService.IPostProtocollo")]
    public interface IPostProtocollo
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/PostProtocollo", ReplyAction="http://tempuri.org/IPostProtocollo/PostProtocolloResponse")]
        bool PostProtocollo(ProtocolloNewService.Documento documento, ProtocolloNewService.Utente utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/PostProtocollo", ReplyAction="http://tempuri.org/IPostProtocollo/PostProtocolloResponse")]
        System.Threading.Tasks.Task<bool> PostProtocolloAsync(ProtocolloNewService.Documento documento, ProtocolloNewService.Utente utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/Spedizioni", ReplyAction="http://tempuri.org/IPostProtocollo/SpedizioniResponse")]
        bool Spedizioni(ProtocolloNewService.Utente utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/Spedizioni", ReplyAction="http://tempuri.org/IPostProtocollo/SpedizioniResponse")]
        System.Threading.Tasks.Task<bool> SpedizioniAsync(ProtocolloNewService.Utente utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/InviaProtcolloPEC", ReplyAction="http://tempuri.org/IPostProtocollo/InviaProtcolloPECResponse")]
        bool InviaProtcolloPEC(ProtocolloNewService.Utente utente, ProtocolloNewService.Documento documento, ProtocolloNewService.Destinatario destinatario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/InviaProtcolloPEC", ReplyAction="http://tempuri.org/IPostProtocollo/InviaProtcolloPECResponse")]
        System.Threading.Tasks.Task<bool> InviaProtcolloPECAsync(ProtocolloNewService.Utente utente, ProtocolloNewService.Documento documento, ProtocolloNewService.Destinatario destinatario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/InviaEmailBulk", ReplyAction="http://tempuri.org/IPostProtocollo/InviaEmailBulkResponse")]
        bool InviaEmailBulk(ProtocolloNewService.Utente utente, ProtocolloNewService.Documento documento, ProtocolloNewService.Ente ente, ProtocolloNewService.Destinatario destinatario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/InviaEmailBulk", ReplyAction="http://tempuri.org/IPostProtocollo/InviaEmailBulkResponse")]
        System.Threading.Tasks.Task<bool> InviaEmailBulkAsync(ProtocolloNewService.Utente utente, ProtocolloNewService.Documento documento, ProtocolloNewService.Ente ente, ProtocolloNewService.Destinatario destinatario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/ProtocolloNew", ReplyAction="http://tempuri.org/IPostProtocollo/ProtocolloNewResponse")]
        ProtocolloNewService.NewProtocollo ProtocolloNew(ProtocolloNewService.Utente utente, ProtocolloNewService.Documento documento, ProtocolloNewService.Ente ente, ProtocolloNewService.Destinatario destinatario, ProtocolloNewService.Allegati allegati, ProtocolloNewService.Fascicolo fascicolo, ProtocolloNewService.FileToSend fileToSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/ProtocolloNew", ReplyAction="http://tempuri.org/IPostProtocollo/ProtocolloNewResponse")]
        System.Threading.Tasks.Task<ProtocolloNewService.NewProtocollo> ProtocolloNewAsync(ProtocolloNewService.Utente utente, ProtocolloNewService.Documento documento, ProtocolloNewService.Ente ente, ProtocolloNewService.Destinatario destinatario, ProtocolloNewService.Allegati allegati, ProtocolloNewService.Fascicolo fascicolo, ProtocolloNewService.FileToSend fileToSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/AllegaDocInterno", ReplyAction="http://tempuri.org/IPostProtocollo/AllegaDocInternoResponse")]
        bool AllegaDocInterno(ProtocolloNewService.Utente utente, ProtocolloNewService.Fascicolo fascicolo, ProtocolloNewService.Documento documento, ProtocolloNewService.FileToSend fileToSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/AllegaDocInterno", ReplyAction="http://tempuri.org/IPostProtocollo/AllegaDocInternoResponse")]
        System.Threading.Tasks.Task<bool> AllegaDocInternoAsync(ProtocolloNewService.Utente utente, ProtocolloNewService.Fascicolo fascicolo, ProtocolloNewService.Documento documento, ProtocolloNewService.FileToSend fileToSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/CreaFascicolo", ReplyAction="http://tempuri.org/IPostProtocollo/CreaFascicoloResponse")]
        string CreaFascicolo(ProtocolloNewService.Utente utente, ProtocolloNewService.Fascicolo fascicolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/CreaFascicolo", ReplyAction="http://tempuri.org/IPostProtocollo/CreaFascicoloResponse")]
        System.Threading.Tasks.Task<string> CreaFascicoloAsync(ProtocolloNewService.Utente utente, ProtocolloNewService.Fascicolo fascicolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDataDocumentoContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDataDocumentoContractResponse")]
        ProtocolloNewService.Documento GetDataDocumentoContract(ProtocolloNewService.Documento documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDataDocumentoContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDataDocumentoContractResponse")]
        System.Threading.Tasks.Task<ProtocolloNewService.Documento> GetDataDocumentoContractAsync(ProtocolloNewService.Documento documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDataUtenteContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDataUtenteContractResponse")]
        ProtocolloNewService.Utente GetDataUtenteContract(ProtocolloNewService.Utente utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDataUtenteContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDataUtenteContractResponse")]
        System.Threading.Tasks.Task<ProtocolloNewService.Utente> GetDataUtenteContractAsync(ProtocolloNewService.Utente utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDataDestinatarioContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDataDestinatarioContractResponse")]
        ProtocolloNewService.Destinatario GetDataDestinatarioContract(ProtocolloNewService.Destinatario destinatario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDataDestinatarioContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDataDestinatarioContractResponse")]
        System.Threading.Tasks.Task<ProtocolloNewService.Destinatario> GetDataDestinatarioContractAsync(ProtocolloNewService.Destinatario destinatario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDataEnteContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDataEnteContractResponse")]
        ProtocolloNewService.Ente GetDataEnteContract(ProtocolloNewService.Ente ente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDataEnteContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDataEnteContractResponse")]
        System.Threading.Tasks.Task<ProtocolloNewService.Ente> GetDataEnteContractAsync(ProtocolloNewService.Ente ente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDataFascicoloContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDataFascicoloContractResponse")]
        ProtocolloNewService.Fascicolo GetDataFascicoloContract(ProtocolloNewService.Fascicolo fascicolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDataFascicoloContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDataFascicoloContractResponse")]
        System.Threading.Tasks.Task<ProtocolloNewService.Fascicolo> GetDataFascicoloContractAsync(ProtocolloNewService.Fascicolo fascicolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDataFileToSendContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDataFileToSendContractResponse")]
        ProtocolloNewService.FileToSend GetDataFileToSendContract(ProtocolloNewService.FileToSend fileToSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDataFileToSendContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDataFileToSendContractResponse")]
        System.Threading.Tasks.Task<ProtocolloNewService.FileToSend> GetDataFileToSendContractAsync(ProtocolloNewService.FileToSend fileToSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDatAllegatiContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDatAllegatiContractResponse")]
        ProtocolloNewService.Allegati GetDatAllegatiContract(ProtocolloNewService.Allegati allegati);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/GetDatAllegatiContract", ReplyAction="http://tempuri.org/IPostProtocollo/GetDatAllegatiContractResponse")]
        System.Threading.Tasks.Task<ProtocolloNewService.Allegati> GetDatAllegatiContractAsync(ProtocolloNewService.Allegati allegati);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/ServiziAssegnatari", ReplyAction="http://tempuri.org/IPostProtocollo/ServiziAssegnatariResponse")]
        ProtocolloNewService.Assegnatari ServiziAssegnatari(ProtocolloNewService.Utente utente, string protocollo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/ServiziAssegnatari", ReplyAction="http://tempuri.org/IPostProtocollo/ServiziAssegnatariResponse")]
        System.Threading.Tasks.Task<ProtocolloNewService.Assegnatari> ServiziAssegnatariAsync(ProtocolloNewService.Utente utente, string protocollo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/RegistraEnte", ReplyAction="http://tempuri.org/IPostProtocollo/RegistraEnteResponse")]
        bool RegistraEnte(int idDoc, string utente, int Tipo, string protocollo, string dataProt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostProtocollo/RegistraEnte", ReplyAction="http://tempuri.org/IPostProtocollo/RegistraEnteResponse")]
        System.Threading.Tasks.Task<bool> RegistraEnteAsync(int idDoc, string utente, int Tipo, string protocollo, string dataProt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IPostProtocolloChannel : ProtocolloNewService.IPostProtocollo, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PostProtocolloClient : System.ServiceModel.ClientBase<ProtocolloNewService.IPostProtocollo>, ProtocolloNewService.IPostProtocollo
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PostProtocolloClient() : 
                base(PostProtocolloClient.GetDefaultBinding(), PostProtocolloClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPostProtocollo.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostProtocolloClient(EndpointConfiguration endpointConfiguration) : 
                base(PostProtocolloClient.GetBindingForEndpoint(endpointConfiguration), PostProtocolloClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostProtocolloClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PostProtocolloClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostProtocolloClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PostProtocolloClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostProtocolloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool PostProtocollo(ProtocolloNewService.Documento documento, ProtocolloNewService.Utente utente)
        {
            return base.Channel.PostProtocollo(documento, utente);
        }
        
        public System.Threading.Tasks.Task<bool> PostProtocolloAsync(ProtocolloNewService.Documento documento, ProtocolloNewService.Utente utente)
        {
            return base.Channel.PostProtocolloAsync(documento, utente);
        }
        
        public bool Spedizioni(ProtocolloNewService.Utente utente)
        {
            return base.Channel.Spedizioni(utente);
        }
        
        public System.Threading.Tasks.Task<bool> SpedizioniAsync(ProtocolloNewService.Utente utente)
        {
            return base.Channel.SpedizioniAsync(utente);
        }
        
        public bool InviaProtcolloPEC(ProtocolloNewService.Utente utente, ProtocolloNewService.Documento documento, ProtocolloNewService.Destinatario destinatario)
        {
            return base.Channel.InviaProtcolloPEC(utente, documento, destinatario);
        }
        
        public System.Threading.Tasks.Task<bool> InviaProtcolloPECAsync(ProtocolloNewService.Utente utente, ProtocolloNewService.Documento documento, ProtocolloNewService.Destinatario destinatario)
        {
            return base.Channel.InviaProtcolloPECAsync(utente, documento, destinatario);
        }
        
        public bool InviaEmailBulk(ProtocolloNewService.Utente utente, ProtocolloNewService.Documento documento, ProtocolloNewService.Ente ente, ProtocolloNewService.Destinatario destinatario)
        {
            return base.Channel.InviaEmailBulk(utente, documento, ente, destinatario);
        }
        
        public System.Threading.Tasks.Task<bool> InviaEmailBulkAsync(ProtocolloNewService.Utente utente, ProtocolloNewService.Documento documento, ProtocolloNewService.Ente ente, ProtocolloNewService.Destinatario destinatario)
        {
            return base.Channel.InviaEmailBulkAsync(utente, documento, ente, destinatario);
        }
        
        public ProtocolloNewService.NewProtocollo ProtocolloNew(ProtocolloNewService.Utente utente, ProtocolloNewService.Documento documento, ProtocolloNewService.Ente ente, ProtocolloNewService.Destinatario destinatario, ProtocolloNewService.Allegati allegati, ProtocolloNewService.Fascicolo fascicolo, ProtocolloNewService.FileToSend fileToSend)
        {
            return base.Channel.ProtocolloNew(utente, documento, ente, destinatario, allegati, fascicolo, fileToSend);
        }
        
        public System.Threading.Tasks.Task<ProtocolloNewService.NewProtocollo> ProtocolloNewAsync(ProtocolloNewService.Utente utente, ProtocolloNewService.Documento documento, ProtocolloNewService.Ente ente, ProtocolloNewService.Destinatario destinatario, ProtocolloNewService.Allegati allegati, ProtocolloNewService.Fascicolo fascicolo, ProtocolloNewService.FileToSend fileToSend)
        {
            return base.Channel.ProtocolloNewAsync(utente, documento, ente, destinatario, allegati, fascicolo, fileToSend);
        }
        
        public bool AllegaDocInterno(ProtocolloNewService.Utente utente, ProtocolloNewService.Fascicolo fascicolo, ProtocolloNewService.Documento documento, ProtocolloNewService.FileToSend fileToSend)
        {
            return base.Channel.AllegaDocInterno(utente, fascicolo, documento, fileToSend);
        }
        
        public System.Threading.Tasks.Task<bool> AllegaDocInternoAsync(ProtocolloNewService.Utente utente, ProtocolloNewService.Fascicolo fascicolo, ProtocolloNewService.Documento documento, ProtocolloNewService.FileToSend fileToSend)
        {
            return base.Channel.AllegaDocInternoAsync(utente, fascicolo, documento, fileToSend);
        }
        
        public string CreaFascicolo(ProtocolloNewService.Utente utente, ProtocolloNewService.Fascicolo fascicolo)
        {
            return base.Channel.CreaFascicolo(utente, fascicolo);
        }
        
        public System.Threading.Tasks.Task<string> CreaFascicoloAsync(ProtocolloNewService.Utente utente, ProtocolloNewService.Fascicolo fascicolo)
        {
            return base.Channel.CreaFascicoloAsync(utente, fascicolo);
        }
        
        public ProtocolloNewService.Documento GetDataDocumentoContract(ProtocolloNewService.Documento documento)
        {
            return base.Channel.GetDataDocumentoContract(documento);
        }
        
        public System.Threading.Tasks.Task<ProtocolloNewService.Documento> GetDataDocumentoContractAsync(ProtocolloNewService.Documento documento)
        {
            return base.Channel.GetDataDocumentoContractAsync(documento);
        }
        
        public ProtocolloNewService.Utente GetDataUtenteContract(ProtocolloNewService.Utente utente)
        {
            return base.Channel.GetDataUtenteContract(utente);
        }
        
        public System.Threading.Tasks.Task<ProtocolloNewService.Utente> GetDataUtenteContractAsync(ProtocolloNewService.Utente utente)
        {
            return base.Channel.GetDataUtenteContractAsync(utente);
        }
        
        public ProtocolloNewService.Destinatario GetDataDestinatarioContract(ProtocolloNewService.Destinatario destinatario)
        {
            return base.Channel.GetDataDestinatarioContract(destinatario);
        }
        
        public System.Threading.Tasks.Task<ProtocolloNewService.Destinatario> GetDataDestinatarioContractAsync(ProtocolloNewService.Destinatario destinatario)
        {
            return base.Channel.GetDataDestinatarioContractAsync(destinatario);
        }
        
        public ProtocolloNewService.Ente GetDataEnteContract(ProtocolloNewService.Ente ente)
        {
            return base.Channel.GetDataEnteContract(ente);
        }
        
        public System.Threading.Tasks.Task<ProtocolloNewService.Ente> GetDataEnteContractAsync(ProtocolloNewService.Ente ente)
        {
            return base.Channel.GetDataEnteContractAsync(ente);
        }
        
        public ProtocolloNewService.Fascicolo GetDataFascicoloContract(ProtocolloNewService.Fascicolo fascicolo)
        {
            return base.Channel.GetDataFascicoloContract(fascicolo);
        }
        
        public System.Threading.Tasks.Task<ProtocolloNewService.Fascicolo> GetDataFascicoloContractAsync(ProtocolloNewService.Fascicolo fascicolo)
        {
            return base.Channel.GetDataFascicoloContractAsync(fascicolo);
        }
        
        public ProtocolloNewService.FileToSend GetDataFileToSendContract(ProtocolloNewService.FileToSend fileToSend)
        {
            return base.Channel.GetDataFileToSendContract(fileToSend);
        }
        
        public System.Threading.Tasks.Task<ProtocolloNewService.FileToSend> GetDataFileToSendContractAsync(ProtocolloNewService.FileToSend fileToSend)
        {
            return base.Channel.GetDataFileToSendContractAsync(fileToSend);
        }
        
        public ProtocolloNewService.Allegati GetDatAllegatiContract(ProtocolloNewService.Allegati allegati)
        {
            return base.Channel.GetDatAllegatiContract(allegati);
        }
        
        public System.Threading.Tasks.Task<ProtocolloNewService.Allegati> GetDatAllegatiContractAsync(ProtocolloNewService.Allegati allegati)
        {
            return base.Channel.GetDatAllegatiContractAsync(allegati);
        }
        
        public ProtocolloNewService.Assegnatari ServiziAssegnatari(ProtocolloNewService.Utente utente, string protocollo)
        {
            return base.Channel.ServiziAssegnatari(utente, protocollo);
        }
        
        public System.Threading.Tasks.Task<ProtocolloNewService.Assegnatari> ServiziAssegnatariAsync(ProtocolloNewService.Utente utente, string protocollo)
        {
            return base.Channel.ServiziAssegnatariAsync(utente, protocollo);
        }
        
        public bool RegistraEnte(int idDoc, string utente, int Tipo, string protocollo, string dataProt)
        {
            return base.Channel.RegistraEnte(idDoc, utente, Tipo, protocollo, dataProt);
        }
        
        public System.Threading.Tasks.Task<bool> RegistraEnteAsync(int idDoc, string utente, int Tipo, string protocollo, string dataProt)
        {
            return base.Channel.RegistraEnteAsync(idDoc, utente, Tipo, protocollo, dataProt);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPostProtocollo))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPostProtocollo))
            {
                return new System.ServiceModel.EndpointAddress("http://sistemaunicoscn.serviziocivile.it/WCFPostProtocollo/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PostProtocolloClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPostProtocollo);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PostProtocolloClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPostProtocollo);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPostProtocollo,
        }
    }
}
