//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtocolloAutenticazioneService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProtocolloAutenticazioneService.SIGED_AUTHSoap")]
    public interface SIGED_AUTHSoap
    {
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento FIRSTNAME dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWS_NEWSESSION", ReplyAction="*")]
        ProtocolloAutenticazioneService.SWS_NEWSESSIONResponse SWS_NEWSESSION(ProtocolloAutenticazioneService.SWS_NEWSESSIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWS_NEWSESSION", ReplyAction="*")]
        System.Threading.Tasks.Task<ProtocolloAutenticazioneService.SWS_NEWSESSIONResponse> SWS_NEWSESSIONAsync(ProtocolloAutenticazioneService.SWS_NEWSESSIONRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento IDSESSION dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWS_CLOSESESSION", ReplyAction="*")]
        ProtocolloAutenticazioneService.SWS_CLOSESESSIONResponse SWS_CLOSESESSION(ProtocolloAutenticazioneService.SWS_CLOSESESSIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWS_CLOSESESSION", ReplyAction="*")]
        System.Threading.Tasks.Task<ProtocolloAutenticazioneService.SWS_CLOSESESSIONResponse> SWS_CLOSESESSIONAsync(ProtocolloAutenticazioneService.SWS_CLOSESESSIONRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento IDSESSION dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWS_RENEWSESSION", ReplyAction="*")]
        ProtocolloAutenticazioneService.SWS_RENEWSESSIONResponse SWS_RENEWSESSION(ProtocolloAutenticazioneService.SWS_RENEWSESSIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWS_RENEWSESSION", ReplyAction="*")]
        System.Threading.Tasks.Task<ProtocolloAutenticazioneService.SWS_RENEWSESSIONResponse> SWS_RENEWSESSIONAsync(ProtocolloAutenticazioneService.SWS_RENEWSESSIONRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento IDSESSION dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWS_STATUSSESSION", ReplyAction="*")]
        ProtocolloAutenticazioneService.SWS_STATUSSESSIONResponse SWS_STATUSSESSION(ProtocolloAutenticazioneService.SWS_STATUSSESSIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWS_STATUSSESSION", ReplyAction="*")]
        System.Threading.Tasks.Task<ProtocolloAutenticazioneService.SWS_STATUSSESSIONResponse> SWS_STATUSSESSIONAsync(ProtocolloAutenticazioneService.SWS_STATUSSESSIONRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SWS_NEWSESSIONRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SWS_NEWSESSION", Namespace="http://tempuri.org/", Order=0)]
        public ProtocolloAutenticazioneService.SWS_NEWSESSIONRequestBody Body;
        
        public SWS_NEWSESSIONRequest()
        {
        }
        
        public SWS_NEWSESSIONRequest(ProtocolloAutenticazioneService.SWS_NEWSESSIONRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SWS_NEWSESSIONRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FIRSTNAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LASTNAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PASSWORD;
        
        public SWS_NEWSESSIONRequestBody()
        {
        }
        
        public SWS_NEWSESSIONRequestBody(string FIRSTNAME, string LASTNAME, string PASSWORD)
        {
            this.FIRSTNAME = FIRSTNAME;
            this.LASTNAME = LASTNAME;
            this.PASSWORD = PASSWORD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SWS_NEWSESSIONResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SWS_NEWSESSIONResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProtocolloAutenticazioneService.SWS_NEWSESSIONResponseBody Body;
        
        public SWS_NEWSESSIONResponse()
        {
        }
        
        public SWS_NEWSESSIONResponse(ProtocolloAutenticazioneService.SWS_NEWSESSIONResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SWS_NEWSESSIONResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SWS_NEWSESSIONResult;
        
        public SWS_NEWSESSIONResponseBody()
        {
        }
        
        public SWS_NEWSESSIONResponseBody(string SWS_NEWSESSIONResult)
        {
            this.SWS_NEWSESSIONResult = SWS_NEWSESSIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SWS_CLOSESESSIONRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SWS_CLOSESESSION", Namespace="http://tempuri.org/", Order=0)]
        public ProtocolloAutenticazioneService.SWS_CLOSESESSIONRequestBody Body;
        
        public SWS_CLOSESESSIONRequest()
        {
        }
        
        public SWS_CLOSESESSIONRequest(ProtocolloAutenticazioneService.SWS_CLOSESESSIONRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SWS_CLOSESESSIONRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDSESSION;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FIRSTNAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LASTNAME;
        
        public SWS_CLOSESESSIONRequestBody()
        {
        }
        
        public SWS_CLOSESESSIONRequestBody(string IDSESSION, string FIRSTNAME, string LASTNAME)
        {
            this.IDSESSION = IDSESSION;
            this.FIRSTNAME = FIRSTNAME;
            this.LASTNAME = LASTNAME;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SWS_CLOSESESSIONResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SWS_CLOSESESSIONResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProtocolloAutenticazioneService.SWS_CLOSESESSIONResponseBody Body;
        
        public SWS_CLOSESESSIONResponse()
        {
        }
        
        public SWS_CLOSESESSIONResponse(ProtocolloAutenticazioneService.SWS_CLOSESESSIONResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SWS_CLOSESESSIONResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SWS_CLOSESESSIONResult;
        
        public SWS_CLOSESESSIONResponseBody()
        {
        }
        
        public SWS_CLOSESESSIONResponseBody(string SWS_CLOSESESSIONResult)
        {
            this.SWS_CLOSESESSIONResult = SWS_CLOSESESSIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SWS_RENEWSESSIONRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SWS_RENEWSESSION", Namespace="http://tempuri.org/", Order=0)]
        public ProtocolloAutenticazioneService.SWS_RENEWSESSIONRequestBody Body;
        
        public SWS_RENEWSESSIONRequest()
        {
        }
        
        public SWS_RENEWSESSIONRequest(ProtocolloAutenticazioneService.SWS_RENEWSESSIONRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SWS_RENEWSESSIONRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDSESSION;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FIRSTNAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LASTNAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PASSWOR;
        
        public SWS_RENEWSESSIONRequestBody()
        {
        }
        
        public SWS_RENEWSESSIONRequestBody(string IDSESSION, string FIRSTNAME, string LASTNAME, string PASSWOR)
        {
            this.IDSESSION = IDSESSION;
            this.FIRSTNAME = FIRSTNAME;
            this.LASTNAME = LASTNAME;
            this.PASSWOR = PASSWOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SWS_RENEWSESSIONResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SWS_RENEWSESSIONResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProtocolloAutenticazioneService.SWS_RENEWSESSIONResponseBody Body;
        
        public SWS_RENEWSESSIONResponse()
        {
        }
        
        public SWS_RENEWSESSIONResponse(ProtocolloAutenticazioneService.SWS_RENEWSESSIONResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SWS_RENEWSESSIONResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SWS_RENEWSESSIONResult;
        
        public SWS_RENEWSESSIONResponseBody()
        {
        }
        
        public SWS_RENEWSESSIONResponseBody(string SWS_RENEWSESSIONResult)
        {
            this.SWS_RENEWSESSIONResult = SWS_RENEWSESSIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SWS_STATUSSESSIONRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SWS_STATUSSESSION", Namespace="http://tempuri.org/", Order=0)]
        public ProtocolloAutenticazioneService.SWS_STATUSSESSIONRequestBody Body;
        
        public SWS_STATUSSESSIONRequest()
        {
        }
        
        public SWS_STATUSSESSIONRequest(ProtocolloAutenticazioneService.SWS_STATUSSESSIONRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SWS_STATUSSESSIONRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDSESSION;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FIRSTNAME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LASTNAME;
        
        public SWS_STATUSSESSIONRequestBody()
        {
        }
        
        public SWS_STATUSSESSIONRequestBody(string IDSESSION, string FIRSTNAME, string LASTNAME)
        {
            this.IDSESSION = IDSESSION;
            this.FIRSTNAME = FIRSTNAME;
            this.LASTNAME = LASTNAME;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SWS_STATUSSESSIONResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SWS_STATUSSESSIONResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProtocolloAutenticazioneService.SWS_STATUSSESSIONResponseBody Body;
        
        public SWS_STATUSSESSIONResponse()
        {
        }
        
        public SWS_STATUSSESSIONResponse(ProtocolloAutenticazioneService.SWS_STATUSSESSIONResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SWS_STATUSSESSIONResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SWS_STATUSSESSIONResult;
        
        public SWS_STATUSSESSIONResponseBody()
        {
        }
        
        public SWS_STATUSSESSIONResponseBody(string SWS_STATUSSESSIONResult)
        {
            this.SWS_STATUSSESSIONResult = SWS_STATUSSESSIONResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SIGED_AUTHSoapChannel : ProtocolloAutenticazioneService.SIGED_AUTHSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SIGED_AUTHSoapClient : System.ServiceModel.ClientBase<ProtocolloAutenticazioneService.SIGED_AUTHSoap>, ProtocolloAutenticazioneService.SIGED_AUTHSoap
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SIGED_AUTHSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SIGED_AUTHSoapClient.GetBindingForEndpoint(endpointConfiguration), SIGED_AUTHSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SIGED_AUTHSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SIGED_AUTHSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SIGED_AUTHSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SIGED_AUTHSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SIGED_AUTHSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProtocolloAutenticazioneService.SWS_NEWSESSIONResponse ProtocolloAutenticazioneService.SIGED_AUTHSoap.SWS_NEWSESSION(ProtocolloAutenticazioneService.SWS_NEWSESSIONRequest request)
        {
            return base.Channel.SWS_NEWSESSION(request);
        }
        
        public string SWS_NEWSESSION(string FIRSTNAME, string LASTNAME, string PASSWORD)
        {
            ProtocolloAutenticazioneService.SWS_NEWSESSIONRequest inValue = new ProtocolloAutenticazioneService.SWS_NEWSESSIONRequest();
            inValue.Body = new ProtocolloAutenticazioneService.SWS_NEWSESSIONRequestBody();
            inValue.Body.FIRSTNAME = FIRSTNAME;
            inValue.Body.LASTNAME = LASTNAME;
            inValue.Body.PASSWORD = PASSWORD;
            ProtocolloAutenticazioneService.SWS_NEWSESSIONResponse retVal = ((ProtocolloAutenticazioneService.SIGED_AUTHSoap)(this)).SWS_NEWSESSION(inValue);
            return retVal.Body.SWS_NEWSESSIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProtocolloAutenticazioneService.SWS_NEWSESSIONResponse> ProtocolloAutenticazioneService.SIGED_AUTHSoap.SWS_NEWSESSIONAsync(ProtocolloAutenticazioneService.SWS_NEWSESSIONRequest request)
        {
            return base.Channel.SWS_NEWSESSIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProtocolloAutenticazioneService.SWS_NEWSESSIONResponse> SWS_NEWSESSIONAsync(string FIRSTNAME, string LASTNAME, string PASSWORD)
        {
            ProtocolloAutenticazioneService.SWS_NEWSESSIONRequest inValue = new ProtocolloAutenticazioneService.SWS_NEWSESSIONRequest();
            inValue.Body = new ProtocolloAutenticazioneService.SWS_NEWSESSIONRequestBody();
            inValue.Body.FIRSTNAME = FIRSTNAME;
            inValue.Body.LASTNAME = LASTNAME;
            inValue.Body.PASSWORD = PASSWORD;
            return ((ProtocolloAutenticazioneService.SIGED_AUTHSoap)(this)).SWS_NEWSESSIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProtocolloAutenticazioneService.SWS_CLOSESESSIONResponse ProtocolloAutenticazioneService.SIGED_AUTHSoap.SWS_CLOSESESSION(ProtocolloAutenticazioneService.SWS_CLOSESESSIONRequest request)
        {
            return base.Channel.SWS_CLOSESESSION(request);
        }
        
        public string SWS_CLOSESESSION(string IDSESSION, string FIRSTNAME, string LASTNAME)
        {
            ProtocolloAutenticazioneService.SWS_CLOSESESSIONRequest inValue = new ProtocolloAutenticazioneService.SWS_CLOSESESSIONRequest();
            inValue.Body = new ProtocolloAutenticazioneService.SWS_CLOSESESSIONRequestBody();
            inValue.Body.IDSESSION = IDSESSION;
            inValue.Body.FIRSTNAME = FIRSTNAME;
            inValue.Body.LASTNAME = LASTNAME;
            ProtocolloAutenticazioneService.SWS_CLOSESESSIONResponse retVal = ((ProtocolloAutenticazioneService.SIGED_AUTHSoap)(this)).SWS_CLOSESESSION(inValue);
            return retVal.Body.SWS_CLOSESESSIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProtocolloAutenticazioneService.SWS_CLOSESESSIONResponse> ProtocolloAutenticazioneService.SIGED_AUTHSoap.SWS_CLOSESESSIONAsync(ProtocolloAutenticazioneService.SWS_CLOSESESSIONRequest request)
        {
            return base.Channel.SWS_CLOSESESSIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProtocolloAutenticazioneService.SWS_CLOSESESSIONResponse> SWS_CLOSESESSIONAsync(string IDSESSION, string FIRSTNAME, string LASTNAME)
        {
            ProtocolloAutenticazioneService.SWS_CLOSESESSIONRequest inValue = new ProtocolloAutenticazioneService.SWS_CLOSESESSIONRequest();
            inValue.Body = new ProtocolloAutenticazioneService.SWS_CLOSESESSIONRequestBody();
            inValue.Body.IDSESSION = IDSESSION;
            inValue.Body.FIRSTNAME = FIRSTNAME;
            inValue.Body.LASTNAME = LASTNAME;
            return ((ProtocolloAutenticazioneService.SIGED_AUTHSoap)(this)).SWS_CLOSESESSIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProtocolloAutenticazioneService.SWS_RENEWSESSIONResponse ProtocolloAutenticazioneService.SIGED_AUTHSoap.SWS_RENEWSESSION(ProtocolloAutenticazioneService.SWS_RENEWSESSIONRequest request)
        {
            return base.Channel.SWS_RENEWSESSION(request);
        }
        
        public string SWS_RENEWSESSION(string IDSESSION, string FIRSTNAME, string LASTNAME, string PASSWOR)
        {
            ProtocolloAutenticazioneService.SWS_RENEWSESSIONRequest inValue = new ProtocolloAutenticazioneService.SWS_RENEWSESSIONRequest();
            inValue.Body = new ProtocolloAutenticazioneService.SWS_RENEWSESSIONRequestBody();
            inValue.Body.IDSESSION = IDSESSION;
            inValue.Body.FIRSTNAME = FIRSTNAME;
            inValue.Body.LASTNAME = LASTNAME;
            inValue.Body.PASSWOR = PASSWOR;
            ProtocolloAutenticazioneService.SWS_RENEWSESSIONResponse retVal = ((ProtocolloAutenticazioneService.SIGED_AUTHSoap)(this)).SWS_RENEWSESSION(inValue);
            return retVal.Body.SWS_RENEWSESSIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProtocolloAutenticazioneService.SWS_RENEWSESSIONResponse> ProtocolloAutenticazioneService.SIGED_AUTHSoap.SWS_RENEWSESSIONAsync(ProtocolloAutenticazioneService.SWS_RENEWSESSIONRequest request)
        {
            return base.Channel.SWS_RENEWSESSIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProtocolloAutenticazioneService.SWS_RENEWSESSIONResponse> SWS_RENEWSESSIONAsync(string IDSESSION, string FIRSTNAME, string LASTNAME, string PASSWOR)
        {
            ProtocolloAutenticazioneService.SWS_RENEWSESSIONRequest inValue = new ProtocolloAutenticazioneService.SWS_RENEWSESSIONRequest();
            inValue.Body = new ProtocolloAutenticazioneService.SWS_RENEWSESSIONRequestBody();
            inValue.Body.IDSESSION = IDSESSION;
            inValue.Body.FIRSTNAME = FIRSTNAME;
            inValue.Body.LASTNAME = LASTNAME;
            inValue.Body.PASSWOR = PASSWOR;
            return ((ProtocolloAutenticazioneService.SIGED_AUTHSoap)(this)).SWS_RENEWSESSIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProtocolloAutenticazioneService.SWS_STATUSSESSIONResponse ProtocolloAutenticazioneService.SIGED_AUTHSoap.SWS_STATUSSESSION(ProtocolloAutenticazioneService.SWS_STATUSSESSIONRequest request)
        {
            return base.Channel.SWS_STATUSSESSION(request);
        }
        
        public string SWS_STATUSSESSION(string IDSESSION, string FIRSTNAME, string LASTNAME)
        {
            ProtocolloAutenticazioneService.SWS_STATUSSESSIONRequest inValue = new ProtocolloAutenticazioneService.SWS_STATUSSESSIONRequest();
            inValue.Body = new ProtocolloAutenticazioneService.SWS_STATUSSESSIONRequestBody();
            inValue.Body.IDSESSION = IDSESSION;
            inValue.Body.FIRSTNAME = FIRSTNAME;
            inValue.Body.LASTNAME = LASTNAME;
            ProtocolloAutenticazioneService.SWS_STATUSSESSIONResponse retVal = ((ProtocolloAutenticazioneService.SIGED_AUTHSoap)(this)).SWS_STATUSSESSION(inValue);
            return retVal.Body.SWS_STATUSSESSIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProtocolloAutenticazioneService.SWS_STATUSSESSIONResponse> ProtocolloAutenticazioneService.SIGED_AUTHSoap.SWS_STATUSSESSIONAsync(ProtocolloAutenticazioneService.SWS_STATUSSESSIONRequest request)
        {
            return base.Channel.SWS_STATUSSESSIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProtocolloAutenticazioneService.SWS_STATUSSESSIONResponse> SWS_STATUSSESSIONAsync(string IDSESSION, string FIRSTNAME, string LASTNAME)
        {
            ProtocolloAutenticazioneService.SWS_STATUSSESSIONRequest inValue = new ProtocolloAutenticazioneService.SWS_STATUSSESSIONRequest();
            inValue.Body = new ProtocolloAutenticazioneService.SWS_STATUSSESSIONRequestBody();
            inValue.Body.IDSESSION = IDSESSION;
            inValue.Body.FIRSTNAME = FIRSTNAME;
            inValue.Body.LASTNAME = LASTNAME;
            return ((ProtocolloAutenticazioneService.SIGED_AUTHSoap)(this)).SWS_STATUSSESSIONAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SIGED_AUTHSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SIGED_AUTHSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SIGED_AUTHSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://testing2008/WSWL/SIGED_AUTH.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SIGED_AUTHSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://testing2008/WSWL/SIGED_AUTH.asmx");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SIGED_AUTHSoap,
            
            SIGED_AUTHSoap12,
        }
    }
}
