//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleAgent.Email {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Intranet/", ConfigurationName="Email.AnagraficaLotusSoap")]
    public interface AnagraficaLotusSoap {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento codicevol dallo spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/Obiettori", ReplyAction="*")]
        ScheduleAgent.Email.ObiettoriResponse Obiettori(ScheduleAgent.Email.ObiettoriRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/Obiettori", ReplyAction="*")]
        System.Threading.Tasks.Task<ScheduleAgent.Email.ObiettoriResponse> ObiettoriAsync(ScheduleAgent.Email.ObiettoriRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento Denominazione dallo spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/AnagrafeSiged", ReplyAction="*")]
        ScheduleAgent.Email.AnagrafeSigedResponse AnagrafeSiged(ScheduleAgent.Email.AnagrafeSigedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/AnagrafeSiged", ReplyAction="*")]
        System.Threading.Tasks.Task<ScheduleAgent.Email.AnagrafeSigedResponse> AnagrafeSigedAsync(ScheduleAgent.Email.AnagrafeSigedRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento Denominazione dallo spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/AnagrafeSigedWs", ReplyAction="*")]
        ScheduleAgent.Email.AnagrafeSigedWsResponse AnagrafeSigedWs(ScheduleAgent.Email.AnagrafeSigedWsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/AnagrafeSigedWs", ReplyAction="*")]
        System.Threading.Tasks.Task<ScheduleAgent.Email.AnagrafeSigedWsResponse> AnagrafeSigedWsAsync(ScheduleAgent.Email.AnagrafeSigedWsRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento codicevol dallo spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/Volontario", ReplyAction="*")]
        ScheduleAgent.Email.VolontarioResponse Volontario(ScheduleAgent.Email.VolontarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/Volontario", ReplyAction="*")]
        System.Threading.Tasks.Task<ScheduleAgent.Email.VolontarioResponse> VolontarioAsync(ScheduleAgent.Email.VolontarioRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento codicevol dallo spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/Enti", ReplyAction="*")]
        ScheduleAgent.Email.EntiResponse Enti(ScheduleAgent.Email.EntiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/Enti", ReplyAction="*")]
        System.Threading.Tasks.Task<ScheduleAgent.Email.EntiResponse> EntiAsync(ScheduleAgent.Email.EntiRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento idFile dallo spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/ScriviDir", ReplyAction="*")]
        ScheduleAgent.Email.ScriviDirResponse ScriviDir(ScheduleAgent.Email.ScriviDirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/ScriviDir", ReplyAction="*")]
        System.Threading.Tasks.Task<ScheduleAgent.Email.ScriviDirResponse> ScriviDirAsync(ScheduleAgent.Email.ScriviDirRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento idFile dallo spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/ScriviDirTest", ReplyAction="*")]
        ScheduleAgent.Email.ScriviDirTestResponse ScriviDirTest(ScheduleAgent.Email.ScriviDirTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/ScriviDirTest", ReplyAction="*")]
        System.Threading.Tasks.Task<ScheduleAgent.Email.ScriviDirTestResponse> ScriviDirTestAsync(ScheduleAgent.Email.ScriviDirTestRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento pathFile dallo spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/ScriviFile", ReplyAction="*")]
        ScheduleAgent.Email.ScriviFileResponse ScriviFile(ScheduleAgent.Email.ScriviFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/ScriviFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ScheduleAgent.Email.ScriviFileResponse> ScriviFileAsync(ScheduleAgent.Email.ScriviFileRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento pathFile dallo spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/LeggiFile", ReplyAction="*")]
        ScheduleAgent.Email.LeggiFileResponse LeggiFile(ScheduleAgent.Email.LeggiFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/LeggiFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ScheduleAgent.Email.LeggiFileResponse> LeggiFileAsync(ScheduleAgent.Email.LeggiFileRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento pathFile dallo spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/LeggiFileByte", ReplyAction="*")]
        ScheduleAgent.Email.LeggiFileByteResponse LeggiFileByte(ScheduleAgent.Email.LeggiFileByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/LeggiFileByte", ReplyAction="*")]
        System.Threading.Tasks.Task<ScheduleAgent.Email.LeggiFileByteResponse> LeggiFileByteAsync(ScheduleAgent.Email.LeggiFileByteRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento indiOri dallo spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/email", ReplyAction="*")]
        ScheduleAgent.Email.emailResponse email(ScheduleAgent.Email.emailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/email", ReplyAction="*")]
        System.Threading.Tasks.Task<ScheduleAgent.Email.emailResponse> emailAsync(ScheduleAgent.Email.emailRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento sNomeFile dallo spazio dei nomi http://Intranet/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/UpdateFileDoc", ReplyAction="*")]
        ScheduleAgent.Email.UpdateFileDocResponse UpdateFileDoc(ScheduleAgent.Email.UpdateFileDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intranet/UpdateFileDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<ScheduleAgent.Email.UpdateFileDocResponse> UpdateFileDocAsync(ScheduleAgent.Email.UpdateFileDocRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObiettoriRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Obiettori", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.ObiettoriRequestBody Body;
        
        public ObiettoriRequest() {
        }
        
        public ObiettoriRequest(ScheduleAgent.Email.ObiettoriRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ObiettoriRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codicevol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cognome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nome;
        
        public ObiettoriRequestBody() {
        }
        
        public ObiettoriRequestBody(string codicevol, string Cognome, string Nome) {
            this.codicevol = codicevol;
            this.Cognome = Cognome;
            this.Nome = Nome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObiettoriResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObiettoriResponse", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.ObiettoriResponseBody Body;
        
        public ObiettoriResponse() {
        }
        
        public ObiettoriResponse(ScheduleAgent.Email.ObiettoriResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ObiettoriResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObiettoriResult;
        
        public ObiettoriResponseBody() {
        }
        
        public ObiettoriResponseBody(string ObiettoriResult) {
            this.ObiettoriResult = ObiettoriResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnagrafeSigedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnagrafeSiged", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.AnagrafeSigedRequestBody Body;
        
        public AnagrafeSigedRequest() {
        }
        
        public AnagrafeSigedRequest(ScheduleAgent.Email.AnagrafeSigedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class AnagrafeSigedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Denominazione;
        
        public AnagrafeSigedRequestBody() {
        }
        
        public AnagrafeSigedRequestBody(string Denominazione) {
            this.Denominazione = Denominazione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnagrafeSigedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnagrafeSigedResponse", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.AnagrafeSigedResponseBody Body;
        
        public AnagrafeSigedResponse() {
        }
        
        public AnagrafeSigedResponse(ScheduleAgent.Email.AnagrafeSigedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class AnagrafeSigedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnagrafeSigedResult;
        
        public AnagrafeSigedResponseBody() {
        }
        
        public AnagrafeSigedResponseBody(string AnagrafeSigedResult) {
            this.AnagrafeSigedResult = AnagrafeSigedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnagrafeSigedWsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnagrafeSigedWs", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.AnagrafeSigedWsRequestBody Body;
        
        public AnagrafeSigedWsRequest() {
        }
        
        public AnagrafeSigedWsRequest(ScheduleAgent.Email.AnagrafeSigedWsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class AnagrafeSigedWsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Denominazione;
        
        public AnagrafeSigedWsRequestBody() {
        }
        
        public AnagrafeSigedWsRequestBody(string Denominazione) {
            this.Denominazione = Denominazione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnagrafeSigedWsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnagrafeSigedWsResponse", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.AnagrafeSigedWsResponseBody Body;
        
        public AnagrafeSigedWsResponse() {
        }
        
        public AnagrafeSigedWsResponse(ScheduleAgent.Email.AnagrafeSigedWsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class AnagrafeSigedWsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnagrafeSigedWsResult;
        
        public AnagrafeSigedWsResponseBody() {
        }
        
        public AnagrafeSigedWsResponseBody(string AnagrafeSigedWsResult) {
            this.AnagrafeSigedWsResult = AnagrafeSigedWsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VolontarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Volontario", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.VolontarioRequestBody Body;
        
        public VolontarioRequest() {
        }
        
        public VolontarioRequest(ScheduleAgent.Email.VolontarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class VolontarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codicevol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cognome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nome;
        
        public VolontarioRequestBody() {
        }
        
        public VolontarioRequestBody(string codicevol, string Cognome, string Nome) {
            this.codicevol = codicevol;
            this.Cognome = Cognome;
            this.Nome = Nome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VolontarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VolontarioResponse", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.VolontarioResponseBody Body;
        
        public VolontarioResponse() {
        }
        
        public VolontarioResponse(ScheduleAgent.Email.VolontarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class VolontarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VolontarioResult;
        
        public VolontarioResponseBody() {
        }
        
        public VolontarioResponseBody(string VolontarioResult) {
            this.VolontarioResult = VolontarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Enti", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.EntiRequestBody Body;
        
        public EntiRequest() {
        }
        
        public EntiRequest(ScheduleAgent.Email.EntiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class EntiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codicevol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Denominazione;
        
        public EntiRequestBody() {
        }
        
        public EntiRequestBody(string codicevol, string Denominazione) {
            this.codicevol = codicevol;
            this.Denominazione = Denominazione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EntiResponse", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.EntiResponseBody Body;
        
        public EntiResponse() {
        }
        
        public EntiResponse(ScheduleAgent.Email.EntiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class EntiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EntiResult;
        
        public EntiResponseBody() {
        }
        
        public EntiResponseBody(string EntiResult) {
            this.EntiResult = EntiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScriviDirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScriviDir", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.ScriviDirRequestBody Body;
        
        public ScriviDirRequest() {
        }
        
        public ScriviDirRequest(ScheduleAgent.Email.ScriviDirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ScriviDirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idFile;
        
        public ScriviDirRequestBody() {
        }
        
        public ScriviDirRequestBody(string idFile) {
            this.idFile = idFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScriviDirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScriviDirResponse", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.ScriviDirResponseBody Body;
        
        public ScriviDirResponse() {
        }
        
        public ScriviDirResponse(ScheduleAgent.Email.ScriviDirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ScriviDirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ScriviDirResult;
        
        public ScriviDirResponseBody() {
        }
        
        public ScriviDirResponseBody(bool ScriviDirResult) {
            this.ScriviDirResult = ScriviDirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScriviDirTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScriviDirTest", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.ScriviDirTestRequestBody Body;
        
        public ScriviDirTestRequest() {
        }
        
        public ScriviDirTestRequest(ScheduleAgent.Email.ScriviDirTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ScriviDirTestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idFile;
        
        public ScriviDirTestRequestBody() {
        }
        
        public ScriviDirTestRequestBody(string idFile) {
            this.idFile = idFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScriviDirTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScriviDirTestResponse", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.ScriviDirTestResponseBody Body;
        
        public ScriviDirTestResponse() {
        }
        
        public ScriviDirTestResponse(ScheduleAgent.Email.ScriviDirTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ScriviDirTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ScriviDirTestResult;
        
        public ScriviDirTestResponseBody() {
        }
        
        public ScriviDirTestResponseBody(bool ScriviDirTestResult) {
            this.ScriviDirTestResult = ScriviDirTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScriviFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScriviFile", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.ScriviFileRequestBody Body;
        
        public ScriviFileRequest() {
        }
        
        public ScriviFileRequest(ScheduleAgent.Email.ScriviFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ScriviFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pathFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomeFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] byteFile;
        
        public ScriviFileRequestBody() {
        }
        
        public ScriviFileRequestBody(string pathFile, string nomeFile, byte[] byteFile) {
            this.pathFile = pathFile;
            this.nomeFile = nomeFile;
            this.byteFile = byteFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScriviFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScriviFileResponse", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.ScriviFileResponseBody Body;
        
        public ScriviFileResponse() {
        }
        
        public ScriviFileResponse(ScheduleAgent.Email.ScriviFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class ScriviFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ScriviFileResult;
        
        public ScriviFileResponseBody() {
        }
        
        public ScriviFileResponseBody(bool ScriviFileResult) {
            this.ScriviFileResult = ScriviFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeggiFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeggiFile", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.LeggiFileRequestBody Body;
        
        public LeggiFileRequest() {
        }
        
        public LeggiFileRequest(ScheduleAgent.Email.LeggiFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class LeggiFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pathFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomeFile;
        
        public LeggiFileRequestBody() {
        }
        
        public LeggiFileRequestBody(string pathFile, string nomeFile) {
            this.pathFile = pathFile;
            this.nomeFile = nomeFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeggiFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeggiFileResponse", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.LeggiFileResponseBody Body;
        
        public LeggiFileResponse() {
        }
        
        public LeggiFileResponse(ScheduleAgent.Email.LeggiFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class LeggiFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LeggiFileResult;
        
        public LeggiFileResponseBody() {
        }
        
        public LeggiFileResponseBody(string LeggiFileResult) {
            this.LeggiFileResult = LeggiFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeggiFileByteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeggiFileByte", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.LeggiFileByteRequestBody Body;
        
        public LeggiFileByteRequest() {
        }
        
        public LeggiFileByteRequest(ScheduleAgent.Email.LeggiFileByteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class LeggiFileByteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pathFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomeFile;
        
        public LeggiFileByteRequestBody() {
        }
        
        public LeggiFileByteRequestBody(string pathFile, string nomeFile) {
            this.pathFile = pathFile;
            this.nomeFile = nomeFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeggiFileByteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeggiFileByteResponse", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.LeggiFileByteResponseBody Body;
        
        public LeggiFileByteResponse() {
        }
        
        public LeggiFileByteResponse(ScheduleAgent.Email.LeggiFileByteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class LeggiFileByteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] LeggiFileByteResult;
        
        public LeggiFileByteResponseBody() {
        }
        
        public LeggiFileByteResponseBody(byte[] LeggiFileByteResult) {
            this.LeggiFileByteResult = LeggiFileByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class emailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="email", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.emailRequestBody Body;
        
        public emailRequest() {
        }
        
        public emailRequest(ScheduleAgent.Email.emailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class emailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string indiOri;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string indiDest;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string oggetto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string corpo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string filetosend;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool produzione;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CC;
        
        public emailRequestBody() {
        }
        
        public emailRequestBody(string indiOri, string indiDest, string oggetto, string corpo, string filetosend, bool produzione, string CC) {
            this.indiOri = indiOri;
            this.indiDest = indiDest;
            this.oggetto = oggetto;
            this.corpo = corpo;
            this.filetosend = filetosend;
            this.produzione = produzione;
            this.CC = CC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class emailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="emailResponse", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.emailResponseBody Body;
        
        public emailResponse() {
        }
        
        public emailResponse(ScheduleAgent.Email.emailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class emailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool emailResult;
        
        public emailResponseBody() {
        }
        
        public emailResponseBody(bool emailResult) {
            this.emailResult = emailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFileDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFileDoc", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.UpdateFileDocRequestBody Body;
        
        public UpdateFileDocRequest() {
        }
        
        public UpdateFileDocRequest(ScheduleAgent.Email.UpdateFileDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class UpdateFileDocRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdFileDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Statomod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sNomeFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sEstensioneFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cuser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Nuser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public byte[] bArray;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] hashAray;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool Determina;
        
        public UpdateFileDocRequestBody() {
        }
        
        public UpdateFileDocRequestBody(int IdFileDoc, int IDDoc, int Statomod, string sNomeFile, string sEstensioneFile, string Cuser, string Nuser, byte[] bArray, byte[] hashAray, bool Determina) {
            this.IdFileDoc = IdFileDoc;
            this.IDDoc = IDDoc;
            this.Statomod = Statomod;
            this.sNomeFile = sNomeFile;
            this.sEstensioneFile = sEstensioneFile;
            this.Cuser = Cuser;
            this.Nuser = Nuser;
            this.bArray = bArray;
            this.hashAray = hashAray;
            this.Determina = Determina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFileDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFileDocResponse", Namespace="http://Intranet/", Order=0)]
        public ScheduleAgent.Email.UpdateFileDocResponseBody Body;
        
        public UpdateFileDocResponse() {
        }
        
        public UpdateFileDocResponse(ScheduleAgent.Email.UpdateFileDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intranet/")]
    public partial class UpdateFileDocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateFileDocResult;
        
        public UpdateFileDocResponseBody() {
        }
        
        public UpdateFileDocResponseBody(bool UpdateFileDocResult) {
            this.UpdateFileDocResult = UpdateFileDocResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AnagraficaLotusSoapChannel : ScheduleAgent.Email.AnagraficaLotusSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnagraficaLotusSoapClient : System.ServiceModel.ClientBase<ScheduleAgent.Email.AnagraficaLotusSoap>, ScheduleAgent.Email.AnagraficaLotusSoap {
        
        public AnagraficaLotusSoapClient() {
        }
        
        public AnagraficaLotusSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnagraficaLotusSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnagraficaLotusSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnagraficaLotusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScheduleAgent.Email.ObiettoriResponse ScheduleAgent.Email.AnagraficaLotusSoap.Obiettori(ScheduleAgent.Email.ObiettoriRequest request) {
            return base.Channel.Obiettori(request);
        }
        
        public string Obiettori(string codicevol, string Cognome, string Nome) {
            ScheduleAgent.Email.ObiettoriRequest inValue = new ScheduleAgent.Email.ObiettoriRequest();
            inValue.Body = new ScheduleAgent.Email.ObiettoriRequestBody();
            inValue.Body.codicevol = codicevol;
            inValue.Body.Cognome = Cognome;
            inValue.Body.Nome = Nome;
            ScheduleAgent.Email.ObiettoriResponse retVal = ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).Obiettori(inValue);
            return retVal.Body.ObiettoriResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScheduleAgent.Email.ObiettoriResponse> ScheduleAgent.Email.AnagraficaLotusSoap.ObiettoriAsync(ScheduleAgent.Email.ObiettoriRequest request) {
            return base.Channel.ObiettoriAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScheduleAgent.Email.ObiettoriResponse> ObiettoriAsync(string codicevol, string Cognome, string Nome) {
            ScheduleAgent.Email.ObiettoriRequest inValue = new ScheduleAgent.Email.ObiettoriRequest();
            inValue.Body = new ScheduleAgent.Email.ObiettoriRequestBody();
            inValue.Body.codicevol = codicevol;
            inValue.Body.Cognome = Cognome;
            inValue.Body.Nome = Nome;
            return ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).ObiettoriAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScheduleAgent.Email.AnagrafeSigedResponse ScheduleAgent.Email.AnagraficaLotusSoap.AnagrafeSiged(ScheduleAgent.Email.AnagrafeSigedRequest request) {
            return base.Channel.AnagrafeSiged(request);
        }
        
        public string AnagrafeSiged(string Denominazione) {
            ScheduleAgent.Email.AnagrafeSigedRequest inValue = new ScheduleAgent.Email.AnagrafeSigedRequest();
            inValue.Body = new ScheduleAgent.Email.AnagrafeSigedRequestBody();
            inValue.Body.Denominazione = Denominazione;
            ScheduleAgent.Email.AnagrafeSigedResponse retVal = ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).AnagrafeSiged(inValue);
            return retVal.Body.AnagrafeSigedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScheduleAgent.Email.AnagrafeSigedResponse> ScheduleAgent.Email.AnagraficaLotusSoap.AnagrafeSigedAsync(ScheduleAgent.Email.AnagrafeSigedRequest request) {
            return base.Channel.AnagrafeSigedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScheduleAgent.Email.AnagrafeSigedResponse> AnagrafeSigedAsync(string Denominazione) {
            ScheduleAgent.Email.AnagrafeSigedRequest inValue = new ScheduleAgent.Email.AnagrafeSigedRequest();
            inValue.Body = new ScheduleAgent.Email.AnagrafeSigedRequestBody();
            inValue.Body.Denominazione = Denominazione;
            return ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).AnagrafeSigedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScheduleAgent.Email.AnagrafeSigedWsResponse ScheduleAgent.Email.AnagraficaLotusSoap.AnagrafeSigedWs(ScheduleAgent.Email.AnagrafeSigedWsRequest request) {
            return base.Channel.AnagrafeSigedWs(request);
        }
        
        public string AnagrafeSigedWs(string Denominazione) {
            ScheduleAgent.Email.AnagrafeSigedWsRequest inValue = new ScheduleAgent.Email.AnagrafeSigedWsRequest();
            inValue.Body = new ScheduleAgent.Email.AnagrafeSigedWsRequestBody();
            inValue.Body.Denominazione = Denominazione;
            ScheduleAgent.Email.AnagrafeSigedWsResponse retVal = ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).AnagrafeSigedWs(inValue);
            return retVal.Body.AnagrafeSigedWsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScheduleAgent.Email.AnagrafeSigedWsResponse> ScheduleAgent.Email.AnagraficaLotusSoap.AnagrafeSigedWsAsync(ScheduleAgent.Email.AnagrafeSigedWsRequest request) {
            return base.Channel.AnagrafeSigedWsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScheduleAgent.Email.AnagrafeSigedWsResponse> AnagrafeSigedWsAsync(string Denominazione) {
            ScheduleAgent.Email.AnagrafeSigedWsRequest inValue = new ScheduleAgent.Email.AnagrafeSigedWsRequest();
            inValue.Body = new ScheduleAgent.Email.AnagrafeSigedWsRequestBody();
            inValue.Body.Denominazione = Denominazione;
            return ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).AnagrafeSigedWsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScheduleAgent.Email.VolontarioResponse ScheduleAgent.Email.AnagraficaLotusSoap.Volontario(ScheduleAgent.Email.VolontarioRequest request) {
            return base.Channel.Volontario(request);
        }
        
        public string Volontario(string codicevol, string Cognome, string Nome) {
            ScheduleAgent.Email.VolontarioRequest inValue = new ScheduleAgent.Email.VolontarioRequest();
            inValue.Body = new ScheduleAgent.Email.VolontarioRequestBody();
            inValue.Body.codicevol = codicevol;
            inValue.Body.Cognome = Cognome;
            inValue.Body.Nome = Nome;
            ScheduleAgent.Email.VolontarioResponse retVal = ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).Volontario(inValue);
            return retVal.Body.VolontarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScheduleAgent.Email.VolontarioResponse> ScheduleAgent.Email.AnagraficaLotusSoap.VolontarioAsync(ScheduleAgent.Email.VolontarioRequest request) {
            return base.Channel.VolontarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScheduleAgent.Email.VolontarioResponse> VolontarioAsync(string codicevol, string Cognome, string Nome) {
            ScheduleAgent.Email.VolontarioRequest inValue = new ScheduleAgent.Email.VolontarioRequest();
            inValue.Body = new ScheduleAgent.Email.VolontarioRequestBody();
            inValue.Body.codicevol = codicevol;
            inValue.Body.Cognome = Cognome;
            inValue.Body.Nome = Nome;
            return ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).VolontarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScheduleAgent.Email.EntiResponse ScheduleAgent.Email.AnagraficaLotusSoap.Enti(ScheduleAgent.Email.EntiRequest request) {
            return base.Channel.Enti(request);
        }
        
        public string Enti(string codicevol, string Denominazione) {
            ScheduleAgent.Email.EntiRequest inValue = new ScheduleAgent.Email.EntiRequest();
            inValue.Body = new ScheduleAgent.Email.EntiRequestBody();
            inValue.Body.codicevol = codicevol;
            inValue.Body.Denominazione = Denominazione;
            ScheduleAgent.Email.EntiResponse retVal = ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).Enti(inValue);
            return retVal.Body.EntiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScheduleAgent.Email.EntiResponse> ScheduleAgent.Email.AnagraficaLotusSoap.EntiAsync(ScheduleAgent.Email.EntiRequest request) {
            return base.Channel.EntiAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScheduleAgent.Email.EntiResponse> EntiAsync(string codicevol, string Denominazione) {
            ScheduleAgent.Email.EntiRequest inValue = new ScheduleAgent.Email.EntiRequest();
            inValue.Body = new ScheduleAgent.Email.EntiRequestBody();
            inValue.Body.codicevol = codicevol;
            inValue.Body.Denominazione = Denominazione;
            return ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).EntiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScheduleAgent.Email.ScriviDirResponse ScheduleAgent.Email.AnagraficaLotusSoap.ScriviDir(ScheduleAgent.Email.ScriviDirRequest request) {
            return base.Channel.ScriviDir(request);
        }
        
        public bool ScriviDir(string idFile) {
            ScheduleAgent.Email.ScriviDirRequest inValue = new ScheduleAgent.Email.ScriviDirRequest();
            inValue.Body = new ScheduleAgent.Email.ScriviDirRequestBody();
            inValue.Body.idFile = idFile;
            ScheduleAgent.Email.ScriviDirResponse retVal = ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).ScriviDir(inValue);
            return retVal.Body.ScriviDirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScheduleAgent.Email.ScriviDirResponse> ScheduleAgent.Email.AnagraficaLotusSoap.ScriviDirAsync(ScheduleAgent.Email.ScriviDirRequest request) {
            return base.Channel.ScriviDirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScheduleAgent.Email.ScriviDirResponse> ScriviDirAsync(string idFile) {
            ScheduleAgent.Email.ScriviDirRequest inValue = new ScheduleAgent.Email.ScriviDirRequest();
            inValue.Body = new ScheduleAgent.Email.ScriviDirRequestBody();
            inValue.Body.idFile = idFile;
            return ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).ScriviDirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScheduleAgent.Email.ScriviDirTestResponse ScheduleAgent.Email.AnagraficaLotusSoap.ScriviDirTest(ScheduleAgent.Email.ScriviDirTestRequest request) {
            return base.Channel.ScriviDirTest(request);
        }
        
        public bool ScriviDirTest(string idFile) {
            ScheduleAgent.Email.ScriviDirTestRequest inValue = new ScheduleAgent.Email.ScriviDirTestRequest();
            inValue.Body = new ScheduleAgent.Email.ScriviDirTestRequestBody();
            inValue.Body.idFile = idFile;
            ScheduleAgent.Email.ScriviDirTestResponse retVal = ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).ScriviDirTest(inValue);
            return retVal.Body.ScriviDirTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScheduleAgent.Email.ScriviDirTestResponse> ScheduleAgent.Email.AnagraficaLotusSoap.ScriviDirTestAsync(ScheduleAgent.Email.ScriviDirTestRequest request) {
            return base.Channel.ScriviDirTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScheduleAgent.Email.ScriviDirTestResponse> ScriviDirTestAsync(string idFile) {
            ScheduleAgent.Email.ScriviDirTestRequest inValue = new ScheduleAgent.Email.ScriviDirTestRequest();
            inValue.Body = new ScheduleAgent.Email.ScriviDirTestRequestBody();
            inValue.Body.idFile = idFile;
            return ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).ScriviDirTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScheduleAgent.Email.ScriviFileResponse ScheduleAgent.Email.AnagraficaLotusSoap.ScriviFile(ScheduleAgent.Email.ScriviFileRequest request) {
            return base.Channel.ScriviFile(request);
        }
        
        public bool ScriviFile(string pathFile, string nomeFile, byte[] byteFile) {
            ScheduleAgent.Email.ScriviFileRequest inValue = new ScheduleAgent.Email.ScriviFileRequest();
            inValue.Body = new ScheduleAgent.Email.ScriviFileRequestBody();
            inValue.Body.pathFile = pathFile;
            inValue.Body.nomeFile = nomeFile;
            inValue.Body.byteFile = byteFile;
            ScheduleAgent.Email.ScriviFileResponse retVal = ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).ScriviFile(inValue);
            return retVal.Body.ScriviFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScheduleAgent.Email.ScriviFileResponse> ScheduleAgent.Email.AnagraficaLotusSoap.ScriviFileAsync(ScheduleAgent.Email.ScriviFileRequest request) {
            return base.Channel.ScriviFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScheduleAgent.Email.ScriviFileResponse> ScriviFileAsync(string pathFile, string nomeFile, byte[] byteFile) {
            ScheduleAgent.Email.ScriviFileRequest inValue = new ScheduleAgent.Email.ScriviFileRequest();
            inValue.Body = new ScheduleAgent.Email.ScriviFileRequestBody();
            inValue.Body.pathFile = pathFile;
            inValue.Body.nomeFile = nomeFile;
            inValue.Body.byteFile = byteFile;
            return ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).ScriviFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScheduleAgent.Email.LeggiFileResponse ScheduleAgent.Email.AnagraficaLotusSoap.LeggiFile(ScheduleAgent.Email.LeggiFileRequest request) {
            return base.Channel.LeggiFile(request);
        }
        
        public string LeggiFile(string pathFile, string nomeFile) {
            ScheduleAgent.Email.LeggiFileRequest inValue = new ScheduleAgent.Email.LeggiFileRequest();
            inValue.Body = new ScheduleAgent.Email.LeggiFileRequestBody();
            inValue.Body.pathFile = pathFile;
            inValue.Body.nomeFile = nomeFile;
            ScheduleAgent.Email.LeggiFileResponse retVal = ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).LeggiFile(inValue);
            return retVal.Body.LeggiFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScheduleAgent.Email.LeggiFileResponse> ScheduleAgent.Email.AnagraficaLotusSoap.LeggiFileAsync(ScheduleAgent.Email.LeggiFileRequest request) {
            return base.Channel.LeggiFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScheduleAgent.Email.LeggiFileResponse> LeggiFileAsync(string pathFile, string nomeFile) {
            ScheduleAgent.Email.LeggiFileRequest inValue = new ScheduleAgent.Email.LeggiFileRequest();
            inValue.Body = new ScheduleAgent.Email.LeggiFileRequestBody();
            inValue.Body.pathFile = pathFile;
            inValue.Body.nomeFile = nomeFile;
            return ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).LeggiFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScheduleAgent.Email.LeggiFileByteResponse ScheduleAgent.Email.AnagraficaLotusSoap.LeggiFileByte(ScheduleAgent.Email.LeggiFileByteRequest request) {
            return base.Channel.LeggiFileByte(request);
        }
        
        public byte[] LeggiFileByte(string pathFile, string nomeFile) {
            ScheduleAgent.Email.LeggiFileByteRequest inValue = new ScheduleAgent.Email.LeggiFileByteRequest();
            inValue.Body = new ScheduleAgent.Email.LeggiFileByteRequestBody();
            inValue.Body.pathFile = pathFile;
            inValue.Body.nomeFile = nomeFile;
            ScheduleAgent.Email.LeggiFileByteResponse retVal = ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).LeggiFileByte(inValue);
            return retVal.Body.LeggiFileByteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScheduleAgent.Email.LeggiFileByteResponse> ScheduleAgent.Email.AnagraficaLotusSoap.LeggiFileByteAsync(ScheduleAgent.Email.LeggiFileByteRequest request) {
            return base.Channel.LeggiFileByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScheduleAgent.Email.LeggiFileByteResponse> LeggiFileByteAsync(string pathFile, string nomeFile) {
            ScheduleAgent.Email.LeggiFileByteRequest inValue = new ScheduleAgent.Email.LeggiFileByteRequest();
            inValue.Body = new ScheduleAgent.Email.LeggiFileByteRequestBody();
            inValue.Body.pathFile = pathFile;
            inValue.Body.nomeFile = nomeFile;
            return ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).LeggiFileByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScheduleAgent.Email.emailResponse ScheduleAgent.Email.AnagraficaLotusSoap.email(ScheduleAgent.Email.emailRequest request) {
            return base.Channel.email(request);
        }
        
        public bool email(string indiOri, string indiDest, string oggetto, string corpo, string filetosend, bool produzione, string CC) {
            ScheduleAgent.Email.emailRequest inValue = new ScheduleAgent.Email.emailRequest();
            inValue.Body = new ScheduleAgent.Email.emailRequestBody();
            inValue.Body.indiOri = indiOri;
            inValue.Body.indiDest = indiDest;
            inValue.Body.oggetto = oggetto;
            inValue.Body.corpo = corpo;
            inValue.Body.filetosend = filetosend;
            inValue.Body.produzione = produzione;
            inValue.Body.CC = CC;
            ScheduleAgent.Email.emailResponse retVal = ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).email(inValue);
            return retVal.Body.emailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScheduleAgent.Email.emailResponse> ScheduleAgent.Email.AnagraficaLotusSoap.emailAsync(ScheduleAgent.Email.emailRequest request) {
            return base.Channel.emailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScheduleAgent.Email.emailResponse> emailAsync(string indiOri, string indiDest, string oggetto, string corpo, string filetosend, bool produzione, string CC) {
            ScheduleAgent.Email.emailRequest inValue = new ScheduleAgent.Email.emailRequest();
            inValue.Body = new ScheduleAgent.Email.emailRequestBody();
            inValue.Body.indiOri = indiOri;
            inValue.Body.indiDest = indiDest;
            inValue.Body.oggetto = oggetto;
            inValue.Body.corpo = corpo;
            inValue.Body.filetosend = filetosend;
            inValue.Body.produzione = produzione;
            inValue.Body.CC = CC;
            return ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).emailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScheduleAgent.Email.UpdateFileDocResponse ScheduleAgent.Email.AnagraficaLotusSoap.UpdateFileDoc(ScheduleAgent.Email.UpdateFileDocRequest request) {
            return base.Channel.UpdateFileDoc(request);
        }
        
        public bool UpdateFileDoc(int IdFileDoc, int IDDoc, int Statomod, string sNomeFile, string sEstensioneFile, string Cuser, string Nuser, byte[] bArray, byte[] hashAray, bool Determina) {
            ScheduleAgent.Email.UpdateFileDocRequest inValue = new ScheduleAgent.Email.UpdateFileDocRequest();
            inValue.Body = new ScheduleAgent.Email.UpdateFileDocRequestBody();
            inValue.Body.IdFileDoc = IdFileDoc;
            inValue.Body.IDDoc = IDDoc;
            inValue.Body.Statomod = Statomod;
            inValue.Body.sNomeFile = sNomeFile;
            inValue.Body.sEstensioneFile = sEstensioneFile;
            inValue.Body.Cuser = Cuser;
            inValue.Body.Nuser = Nuser;
            inValue.Body.bArray = bArray;
            inValue.Body.hashAray = hashAray;
            inValue.Body.Determina = Determina;
            ScheduleAgent.Email.UpdateFileDocResponse retVal = ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).UpdateFileDoc(inValue);
            return retVal.Body.UpdateFileDocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScheduleAgent.Email.UpdateFileDocResponse> ScheduleAgent.Email.AnagraficaLotusSoap.UpdateFileDocAsync(ScheduleAgent.Email.UpdateFileDocRequest request) {
            return base.Channel.UpdateFileDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScheduleAgent.Email.UpdateFileDocResponse> UpdateFileDocAsync(int IdFileDoc, int IDDoc, int Statomod, string sNomeFile, string sEstensioneFile, string Cuser, string Nuser, byte[] bArray, byte[] hashAray, bool Determina) {
            ScheduleAgent.Email.UpdateFileDocRequest inValue = new ScheduleAgent.Email.UpdateFileDocRequest();
            inValue.Body = new ScheduleAgent.Email.UpdateFileDocRequestBody();
            inValue.Body.IdFileDoc = IdFileDoc;
            inValue.Body.IDDoc = IDDoc;
            inValue.Body.Statomod = Statomod;
            inValue.Body.sNomeFile = sNomeFile;
            inValue.Body.sEstensioneFile = sEstensioneFile;
            inValue.Body.Cuser = Cuser;
            inValue.Body.Nuser = Nuser;
            inValue.Body.bArray = bArray;
            inValue.Body.hashAray = hashAray;
            inValue.Body.Determina = Determina;
            return ((ScheduleAgent.Email.AnagraficaLotusSoap)(this)).UpdateFileDocAsync(inValue);
        }
    }
}
