//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomandeOnline.Autenticazione {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/WSAUTENTICAZIONE/wsAutenticazione", ConfigurationName="Autenticazione.wsAutenticazioneSoap")]
    public interface wsAutenticazioneSoap {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento username dallo spazio dei nomi http://tempuri.org/WSAUTENTICAZIONE/wsAutenticazione non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSAUTENTICAZIONE/wsAutenticazione/EseguiAutenticazione", ReplyAction="*")]
        DomandeOnline.Autenticazione.EseguiAutenticazioneResponse EseguiAutenticazione(DomandeOnline.Autenticazione.EseguiAutenticazioneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSAUTENTICAZIONE/wsAutenticazione/EseguiAutenticazione", ReplyAction="*")]
        System.Threading.Tasks.Task<DomandeOnline.Autenticazione.EseguiAutenticazioneResponse> EseguiAutenticazioneAsync(DomandeOnline.Autenticazione.EseguiAutenticazioneRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EseguiAutenticazioneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EseguiAutenticazione", Namespace="http://tempuri.org/WSAUTENTICAZIONE/wsAutenticazione", Order=0)]
        public DomandeOnline.Autenticazione.EseguiAutenticazioneRequestBody Body;
        
        public EseguiAutenticazioneRequest() {
        }
        
        public EseguiAutenticazioneRequest(DomandeOnline.Autenticazione.EseguiAutenticazioneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WSAUTENTICAZIONE/wsAutenticazione")]
    public partial class EseguiAutenticazioneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public EseguiAutenticazioneRequestBody() {
        }
        
        public EseguiAutenticazioneRequestBody(string username, string pwd) {
            this.username = username;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EseguiAutenticazioneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EseguiAutenticazioneResponse", Namespace="http://tempuri.org/WSAUTENTICAZIONE/wsAutenticazione", Order=0)]
        public DomandeOnline.Autenticazione.EseguiAutenticazioneResponseBody Body;
        
        public EseguiAutenticazioneResponse() {
        }
        
        public EseguiAutenticazioneResponse(DomandeOnline.Autenticazione.EseguiAutenticazioneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WSAUTENTICAZIONE/wsAutenticazione")]
    public partial class EseguiAutenticazioneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EseguiAutenticazioneResult;
        
        public EseguiAutenticazioneResponseBody() {
        }
        
        public EseguiAutenticazioneResponseBody(string EseguiAutenticazioneResult) {
            this.EseguiAutenticazioneResult = EseguiAutenticazioneResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAutenticazioneSoapChannel : DomandeOnline.Autenticazione.wsAutenticazioneSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAutenticazioneSoapClient : System.ServiceModel.ClientBase<DomandeOnline.Autenticazione.wsAutenticazioneSoap>, DomandeOnline.Autenticazione.wsAutenticazioneSoap {
        
        public wsAutenticazioneSoapClient() {
        }
        
        public wsAutenticazioneSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAutenticazioneSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAutenticazioneSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAutenticazioneSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DomandeOnline.Autenticazione.EseguiAutenticazioneResponse DomandeOnline.Autenticazione.wsAutenticazioneSoap.EseguiAutenticazione(DomandeOnline.Autenticazione.EseguiAutenticazioneRequest request) {
            return base.Channel.EseguiAutenticazione(request);
        }
        
        public string EseguiAutenticazione(string username, string pwd) {
            DomandeOnline.Autenticazione.EseguiAutenticazioneRequest inValue = new DomandeOnline.Autenticazione.EseguiAutenticazioneRequest();
            inValue.Body = new DomandeOnline.Autenticazione.EseguiAutenticazioneRequestBody();
            inValue.Body.username = username;
            inValue.Body.pwd = pwd;
            DomandeOnline.Autenticazione.EseguiAutenticazioneResponse retVal = ((DomandeOnline.Autenticazione.wsAutenticazioneSoap)(this)).EseguiAutenticazione(inValue);
            return retVal.Body.EseguiAutenticazioneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DomandeOnline.Autenticazione.EseguiAutenticazioneResponse> DomandeOnline.Autenticazione.wsAutenticazioneSoap.EseguiAutenticazioneAsync(DomandeOnline.Autenticazione.EseguiAutenticazioneRequest request) {
            return base.Channel.EseguiAutenticazioneAsync(request);
        }
        
        public System.Threading.Tasks.Task<DomandeOnline.Autenticazione.EseguiAutenticazioneResponse> EseguiAutenticazioneAsync(string username, string pwd) {
            DomandeOnline.Autenticazione.EseguiAutenticazioneRequest inValue = new DomandeOnline.Autenticazione.EseguiAutenticazioneRequest();
            inValue.Body = new DomandeOnline.Autenticazione.EseguiAutenticazioneRequestBody();
            inValue.Body.username = username;
            inValue.Body.pwd = pwd;
            return ((DomandeOnline.Autenticazione.wsAutenticazioneSoap)(this)).EseguiAutenticazioneAsync(inValue);
        }
    }
}
